// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APITokensColumns holds the columns for the "api_tokens" table.
	APITokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "token_prefix", Type: field.TypeString, Default: ""},
		{Name: "scopes", Type: field.TypeString, Default: ""},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "use_count", Type: field.TypeInt64, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// APITokensTable holds the schema information for the "api_tokens" table.
	APITokensTable = &schema.Table{
		Name:       "api_tokens",
		Columns:    APITokensColumns,
		PrimaryKey: []*schema.Column{APITokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apitoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{APITokensColumns[1]},
			},
			{
				Name:    "apitoken_token_hash",
				Unique:  false,
				Columns: []*schema.Column{APITokensColumns[3]},
			},
		},
	}
	// ApprovalPoliciesColumns holds the columns for the "approval_policies" table.
	ApprovalPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "conditions", Type: field.TypeString, Default: "{}"},
		{Name: "approval_chain", Type: field.TypeString, Default: "[]"},
		{Name: "auto_approve_enabled", Type: field.TypeBool, Default: false},
		{Name: "auto_approve_reason", Type: field.TypeString, Nullable: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// ApprovalPoliciesTable holds the schema information for the "approval_policies" table.
	ApprovalPoliciesTable = &schema.Table{
		Name:       "approval_policies",
		Columns:    ApprovalPoliciesColumns,
		PrimaryKey: []*schema.Column{ApprovalPoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "approvalpolicy_enabled_priority",
				Unique:  false,
				Columns: []*schema.Column{ApprovalPoliciesColumns[3], ApprovalPoliciesColumns[4]},
			},
		},
	}
	// ApprovalRecordsColumns holds the columns for the "approval_records" table.
	ApprovalRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ticket_id", Type: field.TypeInt64},
		{Name: "policy_id", Type: field.TypeInt64, Nullable: true},
		{Name: "stage", Type: field.TypeInt, Default: 0},
		{Name: "total_stages", Type: field.TypeInt, Default: 0},
		{Name: "approver_role", Type: field.TypeString, Default: ""},
		{Name: "approver_id", Type: field.TypeInt64, Nullable: true},
		{Name: "approver_name", Type: field.TypeString, Nullable: true},
		{Name: "action", Type: field.TypeString, Default: ""},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "auto_approved", Type: field.TypeBool, Default: false},
		{Name: "auto_reason", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// ApprovalRecordsTable holds the schema information for the "approval_records" table.
	ApprovalRecordsTable = &schema.Table{
		Name:       "approval_records",
		Columns:    ApprovalRecordsColumns,
		PrimaryKey: []*schema.Column{ApprovalRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "approvalrecord_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{ApprovalRecordsColumns[1]},
			},
			{
				Name:    "approvalrecord_approver_id",
				Unique:  false,
				Columns: []*schema.Column{ApprovalRecordsColumns[6]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "action", Type: field.TypeString, Default: ""},
		{Name: "datasource_id", Type: field.TypeInt64, Default: 0},
		{Name: "database", Type: field.TypeString, Default: ""},
		{Name: "sql_content", Type: field.TypeString, Default: ""},
		{Name: "sql_summary", Type: field.TypeString, Default: ""},
		{Name: "result_rows", Type: field.TypeInt64, Default: 0},
		{Name: "affected_rows", Type: field.TypeInt64, Default: 0},
		{Name: "execution_time_ms", Type: field.TypeInt64, Default: 0},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "desensitized_fields", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
		{Name: "ai_review_result", Type: field.TypeString, Default: ""},
		{Name: "ticket_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_user_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[2]},
			},
			{
				Name:    "auditlog_datasource_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3]},
			},
			{
				Name:    "auditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[15]},
			},
			{
				Name:    "auditlog_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[14]},
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "content", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "comment_order_id",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[1]},
			},
			{
				Name:    "comment_parent_id",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[4]},
			},
		},
	}
	// DatasourcesColumns holds the columns for the "datasources" table.
	DatasourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "host", Type: field.TypeString},
		{Name: "port", Type: field.TypeInt},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "password_encrypted", Type: field.TypeString, Default: ""},
		{Name: "database", Type: field.TypeString, Default: ""},
		{Name: "max_open", Type: field.TypeInt, Default: 10},
		{Name: "max_idle", Type: field.TypeInt, Default: 5},
		{Name: "max_lifetime", Type: field.TypeInt, Default: 3600},
		{Name: "max_idle_time", Type: field.TypeInt, Default: 600},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "sslmode", Type: field.TypeString, Default: ""},
		{Name: "schema_name", Type: field.TypeString, Default: ""},
		{Name: "es_urls", Type: field.TypeString, Default: ""},
		{Name: "es_version", Type: field.TypeString, Default: ""},
		{Name: "es_auth_type", Type: field.TypeString, Default: ""},
		{Name: "es_api_key", Type: field.TypeString, Default: ""},
		{Name: "es_index_pattern", Type: field.TypeString, Default: ""},
		{Name: "es_verify_certs", Type: field.TypeBool, Default: true},
		{Name: "extra_config", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// DatasourcesTable holds the schema information for the "datasources" table.
	DatasourcesTable = &schema.Table{
		Name:       "datasources",
		Columns:    DatasourcesColumns,
		PrimaryKey: []*schema.Column{DatasourcesColumns[0]},
	}
	// ExecutionResultsColumns holds the columns for the "execution_results" table.
	ExecutionResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ticket_id", Type: field.TypeInt64},
		{Name: "statement_index", Type: field.TypeInt, Default: 0},
		{Name: "sql", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "rows_affected", Type: field.TypeInt64, Default: 0},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// ExecutionResultsTable holds the schema information for the "execution_results" table.
	ExecutionResultsTable = &schema.Table{
		Name:       "execution_results",
		Columns:    ExecutionResultsColumns,
		PrimaryKey: []*schema.Column{ExecutionResultsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "executionresult_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutionResultsColumns[1]},
			},
		},
	}
	// ExportTasksColumns holds the columns for the "export_tasks" table.
	ExportTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "export_type", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "filename", Type: field.TypeString, Default: ""},
		{Name: "file_path", Type: field.TypeString, Default: ""},
		{Name: "total_rows", Type: field.TypeInt64, Default: 0},
		{Name: "file_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "filters_json", Type: field.TypeString, Default: "{}"},
		{Name: "error_msg", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// ExportTasksTable holds the schema information for the "export_tasks" table.
	ExportTasksTable = &schema.Table{
		Name:       "export_tasks",
		Columns:    ExportTasksColumns,
		PrimaryKey: []*schema.Column{ExportTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "exporttask_user_id",
				Unique:  false,
				Columns: []*schema.Column{ExportTasksColumns[1]},
			},
			{
				Name:    "exporttask_status",
				Unique:  false,
				Columns: []*schema.Column{ExportTasksColumns[4]},
			},
		},
	}
	// GitLinksColumns holds the columns for the "git_links" table.
	GitLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "entity_type", Type: field.TypeString, Default: "ticket"},
		{Name: "entity_id", Type: field.TypeInt64, Default: 0},
		{Name: "link_type", Type: field.TypeString, Default: "commit"},
		{Name: "commit_hash", Type: field.TypeString, Default: ""},
		{Name: "commit_msg", Type: field.TypeString, Default: ""},
		{Name: "author_name", Type: field.TypeString, Default: ""},
		{Name: "author_email", Type: field.TypeString, Default: ""},
		{Name: "pr_number", Type: field.TypeInt, Default: 0},
		{Name: "pr_title", Type: field.TypeString, Default: ""},
		{Name: "pr_url", Type: field.TypeString, Default: ""},
		{Name: "repo_url", Type: field.TypeString, Default: ""},
		{Name: "branch", Type: field.TypeString, Default: ""},
		{Name: "created_by", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// GitLinksTable holds the schema information for the "git_links" table.
	GitLinksTable = &schema.Table{
		Name:       "git_links",
		Columns:    GitLinksColumns,
		PrimaryKey: []*schema.Column{GitLinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gitlink_entity_type_entity_id",
				Unique:  false,
				Columns: []*schema.Column{GitLinksColumns[1], GitLinksColumns[2]},
			},
		},
	}
	// MaskRulesColumns holds the columns for the "mask_rules" table.
	MaskRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "datasource_id", Type: field.TypeInt64, Default: 0},
		{Name: "database", Type: field.TypeString, Default: ""},
		{Name: "table_name", Type: field.TypeString, Default: ""},
		{Name: "field", Type: field.TypeString, Default: ""},
		{Name: "mask_type", Type: field.TypeString, Default: ""},
		{Name: "custom_regex", Type: field.TypeString, Default: ""},
		{Name: "custom_template", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// MaskRulesTable holds the schema information for the "mask_rules" table.
	MaskRulesTable = &schema.Table{
		Name:       "mask_rules",
		Columns:    MaskRulesColumns,
		PrimaryKey: []*schema.Column{MaskRulesColumns[0]},
	}
	// OidcProvidersColumns holds the columns for the "oidc_providers" table.
	OidcProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "issuer", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "client_secret", Type: field.TypeString, Default: ""},
		{Name: "scopes", Type: field.TypeString, Default: "openid profile email"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// OidcProvidersTable holds the schema information for the "oidc_providers" table.
	OidcProvidersTable = &schema.Table{
		Name:       "oidc_providers",
		Columns:    OidcProvidersColumns,
		PrimaryKey: []*schema.Column{OidcProvidersColumns[0]},
	}
	// PermissionRequestsColumns holds the columns for the "permission_requests" table.
	PermissionRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "applicant_id", Type: field.TypeInt64},
		{Name: "datasource_id", Type: field.TypeInt64},
		{Name: "database", Type: field.TypeString},
		{Name: "table_name", Type: field.TypeString, Default: ""},
		{Name: "actions", Type: field.TypeString, Default: ""},
		{Name: "reason", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "approver_id", Type: field.TypeInt64, Nullable: true},
		{Name: "approve_comment", Type: field.TypeString, Default: ""},
		{Name: "approved_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_by", Type: field.TypeInt64, Nullable: true},
		{Name: "revoke_reason", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// PermissionRequestsTable holds the schema information for the "permission_requests" table.
	PermissionRequestsTable = &schema.Table{
		Name:       "permission_requests",
		Columns:    PermissionRequestsColumns,
		PrimaryKey: []*schema.Column{PermissionRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permissionrequest_applicant_id",
				Unique:  false,
				Columns: []*schema.Column{PermissionRequestsColumns[1]},
			},
			{
				Name:    "permissionrequest_status",
				Unique:  false,
				Columns: []*schema.Column{PermissionRequestsColumns[7]},
			},
			{
				Name:    "permissionrequest_datasource_id_database",
				Unique:  false,
				Columns: []*schema.Column{PermissionRequestsColumns[2], PermissionRequestsColumns[3]},
			},
		},
	}
	// QueryHistoryColumns holds the columns for the "query_history" table.
	QueryHistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "datasource_id", Type: field.TypeInt64},
		{Name: "database", Type: field.TypeString, Default: ""},
		{Name: "sql_content", Type: field.TypeString},
		{Name: "sql_summary", Type: field.TypeString, Default: ""},
		{Name: "db_type", Type: field.TypeString, Default: "mysql"},
		{Name: "execution_time", Type: field.TypeInt64, Default: 0},
		{Name: "result_rows", Type: field.TypeInt64, Default: 0},
		{Name: "affected_rows", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// QueryHistoryTable holds the schema information for the "query_history" table.
	QueryHistoryTable = &schema.Table{
		Name:       "query_history",
		Columns:    QueryHistoryColumns,
		PrimaryKey: []*schema.Column{QueryHistoryColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "queryhistory_user_id",
				Unique:  false,
				Columns: []*schema.Column{QueryHistoryColumns[1]},
			},
			{
				Name:    "queryhistory_execution_time",
				Unique:  false,
				Columns: []*schema.Column{QueryHistoryColumns[7]},
			},
			{
				Name:    "queryhistory_created_at",
				Unique:  false,
				Columns: []*schema.Column{QueryHistoryColumns[10]},
			},
		},
	}
	// QuerySnapshotsColumns holds the columns for the "query_snapshots" table.
	QuerySnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "label", Type: field.TypeString, Default: ""},
		{Name: "columns", Type: field.TypeString},
		{Name: "rows", Type: field.TypeString},
		{Name: "row_count", Type: field.TypeInt64, Default: 0},
		{Name: "query_history_id", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// QuerySnapshotsTable holds the schema information for the "query_snapshots" table.
	QuerySnapshotsTable = &schema.Table{
		Name:       "query_snapshots",
		Columns:    QuerySnapshotsColumns,
		PrimaryKey: []*schema.Column{QuerySnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "querysnapshot_user_id",
				Unique:  false,
				Columns: []*schema.Column{QuerySnapshotsColumns[1]},
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "refreshtoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{RefreshTokensColumns[1]},
			},
			{
				Name:    "refreshtoken_token",
				Unique:  false,
				Columns: []*schema.Column{RefreshTokensColumns[2]},
			},
		},
	}
	// SLAActionLogColumns holds the columns for the "sla_action_log" table.
	SLAActionLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ticket_id", Type: field.TypeInt64},
		{Name: "action_type", Type: field.TypeString},
		{Name: "dedup_key", Type: field.TypeString, Unique: true},
		{Name: "notified_user", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "sla_config_id", Type: field.TypeInt64, Nullable: true},
	}
	// SLAActionLogTable holds the schema information for the "sla_action_log" table.
	SLAActionLogTable = &schema.Table{
		Name:       "sla_action_log",
		Columns:    SLAActionLogColumns,
		PrimaryKey: []*schema.Column{SLAActionLogColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "slaactionlog_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{SLAActionLogColumns[1]},
			},
			{
				Name:    "slaactionlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{SLAActionLogColumns[5]},
			},
		},
	}
	// SLAConfigColumns holds the columns for the "sla_config" table.
	SLAConfigColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "priority", Type: field.TypeString},
		{Name: "timeout_minutes", Type: field.TypeInt},
		{Name: "reminder_percent", Type: field.TypeInt, Default: 80},
		{Name: "escalate_to_role", Type: field.TypeString, Default: "admin"},
		{Name: "escalate_to_user", Type: field.TypeString, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// SLAConfigTable holds the schema information for the "sla_config" table.
	SLAConfigTable = &schema.Table{
		Name:       "sla_config",
		Columns:    SLAConfigColumns,
		PrimaryKey: []*schema.Column{SLAConfigColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "slaconfig_priority",
				Unique:  true,
				Columns: []*schema.Column{SLAConfigColumns[1]},
			},
		},
	}
	// SQLTemplatesColumns holds the columns for the "sql_templates" table.
	SQLTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "sql_content", Type: field.TypeString},
		{Name: "db_type", Type: field.TypeString, Default: "mysql"},
		{Name: "category", Type: field.TypeString, Default: "general"},
		{Name: "params_json", Type: field.TypeString, Default: "[]"},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// SQLTemplatesTable holds the schema information for the "sql_templates" table.
	SQLTemplatesTable = &schema.Table{
		Name:       "sql_templates",
		Columns:    SQLTemplatesColumns,
		PrimaryKey: []*schema.Column{SQLTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sqltemplate_user_id",
				Unique:  false,
				Columns: []*schema.Column{SQLTemplatesColumns[1]},
			},
			{
				Name:    "sqltemplate_category",
				Unique:  false,
				Columns: []*schema.Column{SQLTemplatesColumns[6]},
			},
			{
				Name:    "sqltemplate_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{SQLTemplatesColumns[1], SQLTemplatesColumns[2]},
			},
		},
	}
	// SensitiveTablesColumns holds the columns for the "sensitive_tables" table.
	SensitiveTablesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "datasource_id", Type: field.TypeInt64, Default: 0},
		{Name: "database", Type: field.TypeString, Default: ""},
		{Name: "table_name", Type: field.TypeString, Default: ""},
		{Name: "sensitivity_level", Type: field.TypeString, Default: "medium"},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// SensitiveTablesTable holds the schema information for the "sensitive_tables" table.
	SensitiveTablesTable = &schema.Table{
		Name:       "sensitive_tables",
		Columns:    SensitiveTablesColumns,
		PrimaryKey: []*schema.Column{SensitiveTablesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sensitivetable_datasource_id_database_table_name",
				Unique:  true,
				Columns: []*schema.Column{SensitiveTablesColumns[1], SensitiveTablesColumns[2], SensitiveTablesColumns[3]},
			},
		},
	}
	// SharedResultsColumns holds the columns for the "shared_results" table.
	SharedResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "columns_json", Type: field.TypeString, Default: "[]"},
		{Name: "rows_json", Type: field.TypeString, Default: "[]"},
		{Name: "row_count", Type: field.TypeInt64, Default: 0},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "password_hash", Type: field.TypeString, Default: ""},
		{Name: "sql_summary", Type: field.TypeString, Default: ""},
		{Name: "datasource_name", Type: field.TypeString, Default: ""},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// SharedResultsTable holds the schema information for the "shared_results" table.
	SharedResultsTable = &schema.Table{
		Name:       "shared_results",
		Columns:    SharedResultsColumns,
		PrimaryKey: []*schema.Column{SharedResultsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sharedresult_token",
				Unique:  false,
				Columns: []*schema.Column{SharedResultsColumns[3]},
			},
			{
				Name:    "sharedresult_user_id",
				Unique:  false,
				Columns: []*schema.Column{SharedResultsColumns[1]},
			},
			{
				Name:    "sharedresult_expires_at",
				Unique:  false,
				Columns: []*schema.Column{SharedResultsColumns[7]},
			},
		},
	}
	// TempPoliciesColumns holds the columns for the "temp_policies" table.
	TempPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sub", Type: field.TypeString},
		{Name: "dom", Type: field.TypeString},
		{Name: "obj", Type: field.TypeString},
		{Name: "act", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// TempPoliciesTable holds the schema information for the "temp_policies" table.
	TempPoliciesTable = &schema.Table{
		Name:       "temp_policies",
		Columns:    TempPoliciesColumns,
		PrimaryKey: []*schema.Column{TempPoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "temppolicy_expires_at",
				Unique:  false,
				Columns: []*schema.Column{TempPoliciesColumns[5]},
			},
			{
				Name:    "temppolicy_sub_dom_obj_act",
				Unique:  true,
				Columns: []*schema.Column{TempPoliciesColumns[1], TempPoliciesColumns[2], TempPoliciesColumns[3], TempPoliciesColumns[4]},
			},
		},
	}
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "submitter_id", Type: field.TypeInt64},
		{Name: "datasource_id", Type: field.TypeInt64},
		{Name: "database", Type: field.TypeString, Default: ""},
		{Name: "sql_content", Type: field.TypeString},
		{Name: "sql_summary", Type: field.TypeString, Default: ""},
		{Name: "sql_type", Type: field.TypeString, Default: ""},
		{Name: "db_type", Type: field.TypeString, Default: "mysql"},
		{Name: "change_reason", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "SUBMITTED"},
		{Name: "affected_tables", Type: field.TypeString, Default: "[]"},
		{Name: "risk_level", Type: field.TypeString, Default: ""},
		{Name: "ai_review_result", Type: field.TypeString, Default: ""},
		{Name: "reviewer_id", Type: field.TypeInt64, Default: 0},
		{Name: "review_comment", Type: field.TypeString, Default: ""},
		{Name: "sql_hash", Type: field.TypeString, Default: ""},
		{Name: "revision", Type: field.TypeInt, Default: 1},
		{Name: "current_stage", Type: field.TypeInt, Default: 0},
		{Name: "total_stages", Type: field.TypeInt, Default: 0},
		{Name: "auto_approved", Type: field.TypeBool, Default: false},
		{Name: "auto_approve_reason", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "policy_id", Type: field.TypeInt64, Nullable: true},
		{Name: "scheduled_at", Type: field.TypeTime, Nullable: true},
		{Name: "executed_at", Type: field.TypeTime, Nullable: true},
		{Name: "sla_deadline", Type: field.TypeTime, Nullable: true},
		{Name: "sla_status", Type: field.TypeString, Default: "normal"},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ticket_submitter_id",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[1]},
			},
			{
				Name:    "ticket_status",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[9]},
			},
			{
				Name:    "ticket_datasource_id",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[2]},
			},
			{
				Name:    "ticket_scheduled_at",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[22]},
			},
			{
				Name:    "ticket_sla_deadline",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[24]},
			},
		},
	}
	// TicketRevisionsColumns holds the columns for the "ticket_revisions" table.
	TicketRevisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ticket_id", Type: field.TypeInt64},
		{Name: "revision", Type: field.TypeInt},
		{Name: "sql_content", Type: field.TypeString},
		{Name: "sql_summary", Type: field.TypeString, Default: ""},
		{Name: "change_reason", Type: field.TypeString, Default: ""},
		{Name: "risk_level", Type: field.TypeString, Default: ""},
		{Name: "ai_review_result", Type: field.TypeString, Default: ""},
		{Name: "reviewer_id", Type: field.TypeInt64, Default: 0},
		{Name: "review_comment", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// TicketRevisionsTable holds the schema information for the "ticket_revisions" table.
	TicketRevisionsTable = &schema.Table{
		Name:       "ticket_revisions",
		Columns:    TicketRevisionsColumns,
		PrimaryKey: []*schema.Column{TicketRevisionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ticketrevision_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{TicketRevisionsColumns[1]},
			},
			{
				Name:    "ticketrevision_ticket_id_revision",
				Unique:  false,
				Columns: []*schema.Column{TicketRevisionsColumns[1], TicketRevisionsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, SchemaType: map[string]string{"sqlite3": "text"}},
		{Name: "role", Type: field.TypeString, Default: "developer"},
		{Name: "dingtalk_user_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "dingtalk_union_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "oidc_subject", Type: field.TypeString, Default: ""},
		{Name: "oidc_provider", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_oidc_subject_oidc_provider",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6], UsersColumns[7]},
			},
		},
	}
	// WebVitalsColumns holds the columns for the "web_vitals" table.
	WebVitalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "metric_name", Type: field.TypeString},
		{Name: "value", Type: field.TypeFloat64},
		{Name: "rating", Type: field.TypeString, Default: ""},
		{Name: "path", Type: field.TypeString, Default: ""},
		{Name: "navigation_type", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("datetime('now')")},
	}
	// WebVitalsTable holds the schema information for the "web_vitals" table.
	WebVitalsTable = &schema.Table{
		Name:       "web_vitals",
		Columns:    WebVitalsColumns,
		PrimaryKey: []*schema.Column{WebVitalsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "webvital_metric_name",
				Unique:  false,
				Columns: []*schema.Column{WebVitalsColumns[1]},
			},
			{
				Name:    "webvital_created_at",
				Unique:  false,
				Columns: []*schema.Column{WebVitalsColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APITokensTable,
		ApprovalPoliciesTable,
		ApprovalRecordsTable,
		AuditLogsTable,
		CommentsTable,
		DatasourcesTable,
		ExecutionResultsTable,
		ExportTasksTable,
		GitLinksTable,
		MaskRulesTable,
		OidcProvidersTable,
		PermissionRequestsTable,
		QueryHistoryTable,
		QuerySnapshotsTable,
		RefreshTokensTable,
		SLAActionLogTable,
		SLAConfigTable,
		SQLTemplatesTable,
		SensitiveTablesTable,
		SharedResultsTable,
		TempPoliciesTable,
		TicketsTable,
		TicketRevisionsTable,
		UsersTable,
		WebVitalsTable,
	}
)

func init() {
	APITokensTable.Annotation = &entsql.Annotation{
		Table: "api_tokens",
	}
	ApprovalPoliciesTable.Annotation = &entsql.Annotation{
		Table: "approval_policies",
	}
	ApprovalRecordsTable.Annotation = &entsql.Annotation{
		Table: "approval_records",
	}
	AuditLogsTable.Annotation = &entsql.Annotation{
		Table: "audit_logs",
	}
	CommentsTable.Annotation = &entsql.Annotation{
		Table: "comments",
	}
	DatasourcesTable.Annotation = &entsql.Annotation{
		Table: "datasources",
	}
	ExecutionResultsTable.Annotation = &entsql.Annotation{
		Table: "execution_results",
	}
	ExportTasksTable.Annotation = &entsql.Annotation{
		Table: "export_tasks",
	}
	GitLinksTable.Annotation = &entsql.Annotation{
		Table: "git_links",
	}
	MaskRulesTable.Annotation = &entsql.Annotation{
		Table: "mask_rules",
	}
	OidcProvidersTable.Annotation = &entsql.Annotation{
		Table: "oidc_providers",
	}
	PermissionRequestsTable.Annotation = &entsql.Annotation{
		Table: "permission_requests",
	}
	QueryHistoryTable.Annotation = &entsql.Annotation{
		Table: "query_history",
	}
	QuerySnapshotsTable.Annotation = &entsql.Annotation{
		Table: "query_snapshots",
	}
	RefreshTokensTable.Annotation = &entsql.Annotation{
		Table: "refresh_tokens",
	}
	SLAActionLogTable.Annotation = &entsql.Annotation{
		Table: "sla_action_log",
	}
	SLAConfigTable.Annotation = &entsql.Annotation{
		Table: "sla_config",
	}
	SQLTemplatesTable.Annotation = &entsql.Annotation{
		Table: "sql_templates",
	}
	SensitiveTablesTable.Annotation = &entsql.Annotation{
		Table: "sensitive_tables",
	}
	SharedResultsTable.Annotation = &entsql.Annotation{
		Table: "shared_results",
	}
	TempPoliciesTable.Annotation = &entsql.Annotation{
		Table: "temp_policies",
	}
	TicketsTable.Annotation = &entsql.Annotation{
		Table: "tickets",
	}
	TicketRevisionsTable.Annotation = &entsql.Annotation{
		Table: "ticket_revisions",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	WebVitalsTable.Annotation = &entsql.Annotation{
		Table: "web_vitals",
	}
}
