// Code generated by ent, DO NOT EDIT.

package sensitivetable

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldID, id))
}

// DatasourceID applies equality check predicate on the "datasource_id" field. It's identical to DatasourceIDEQ.
func DatasourceID(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldDatasourceID, v))
}

// Database applies equality check predicate on the "database" field. It's identical to DatabaseEQ.
func Database(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldDatabase, v))
}

// TableName applies equality check predicate on the "table_name" field. It's identical to TableNameEQ.
func TableName(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldTableName, v))
}

// SensitivityLevel applies equality check predicate on the "sensitivity_level" field. It's identical to SensitivityLevelEQ.
func SensitivityLevel(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldSensitivityLevel, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldUpdatedAt, v))
}

// DatasourceIDEQ applies the EQ predicate on the "datasource_id" field.
func DatasourceIDEQ(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldDatasourceID, v))
}

// DatasourceIDNEQ applies the NEQ predicate on the "datasource_id" field.
func DatasourceIDNEQ(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldDatasourceID, v))
}

// DatasourceIDIn applies the In predicate on the "datasource_id" field.
func DatasourceIDIn(vs ...int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldDatasourceID, vs...))
}

// DatasourceIDNotIn applies the NotIn predicate on the "datasource_id" field.
func DatasourceIDNotIn(vs ...int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldDatasourceID, vs...))
}

// DatasourceIDGT applies the GT predicate on the "datasource_id" field.
func DatasourceIDGT(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldDatasourceID, v))
}

// DatasourceIDGTE applies the GTE predicate on the "datasource_id" field.
func DatasourceIDGTE(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldDatasourceID, v))
}

// DatasourceIDLT applies the LT predicate on the "datasource_id" field.
func DatasourceIDLT(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldDatasourceID, v))
}

// DatasourceIDLTE applies the LTE predicate on the "datasource_id" field.
func DatasourceIDLTE(v int64) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldDatasourceID, v))
}

// DatabaseEQ applies the EQ predicate on the "database" field.
func DatabaseEQ(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldDatabase, v))
}

// DatabaseNEQ applies the NEQ predicate on the "database" field.
func DatabaseNEQ(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldDatabase, v))
}

// DatabaseIn applies the In predicate on the "database" field.
func DatabaseIn(vs ...string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldDatabase, vs...))
}

// DatabaseNotIn applies the NotIn predicate on the "database" field.
func DatabaseNotIn(vs ...string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldDatabase, vs...))
}

// DatabaseGT applies the GT predicate on the "database" field.
func DatabaseGT(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldDatabase, v))
}

// DatabaseGTE applies the GTE predicate on the "database" field.
func DatabaseGTE(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldDatabase, v))
}

// DatabaseLT applies the LT predicate on the "database" field.
func DatabaseLT(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldDatabase, v))
}

// DatabaseLTE applies the LTE predicate on the "database" field.
func DatabaseLTE(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldDatabase, v))
}

// DatabaseContains applies the Contains predicate on the "database" field.
func DatabaseContains(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldContains(FieldDatabase, v))
}

// DatabaseHasPrefix applies the HasPrefix predicate on the "database" field.
func DatabaseHasPrefix(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldHasPrefix(FieldDatabase, v))
}

// DatabaseHasSuffix applies the HasSuffix predicate on the "database" field.
func DatabaseHasSuffix(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldHasSuffix(FieldDatabase, v))
}

// DatabaseEqualFold applies the EqualFold predicate on the "database" field.
func DatabaseEqualFold(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEqualFold(FieldDatabase, v))
}

// DatabaseContainsFold applies the ContainsFold predicate on the "database" field.
func DatabaseContainsFold(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldContainsFold(FieldDatabase, v))
}

// TableNameEQ applies the EQ predicate on the "table_name" field.
func TableNameEQ(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldTableName, v))
}

// TableNameNEQ applies the NEQ predicate on the "table_name" field.
func TableNameNEQ(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldTableName, v))
}

// TableNameIn applies the In predicate on the "table_name" field.
func TableNameIn(vs ...string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldTableName, vs...))
}

// TableNameNotIn applies the NotIn predicate on the "table_name" field.
func TableNameNotIn(vs ...string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldTableName, vs...))
}

// TableNameGT applies the GT predicate on the "table_name" field.
func TableNameGT(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldTableName, v))
}

// TableNameGTE applies the GTE predicate on the "table_name" field.
func TableNameGTE(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldTableName, v))
}

// TableNameLT applies the LT predicate on the "table_name" field.
func TableNameLT(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldTableName, v))
}

// TableNameLTE applies the LTE predicate on the "table_name" field.
func TableNameLTE(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldTableName, v))
}

// TableNameContains applies the Contains predicate on the "table_name" field.
func TableNameContains(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldContains(FieldTableName, v))
}

// TableNameHasPrefix applies the HasPrefix predicate on the "table_name" field.
func TableNameHasPrefix(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldHasPrefix(FieldTableName, v))
}

// TableNameHasSuffix applies the HasSuffix predicate on the "table_name" field.
func TableNameHasSuffix(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldHasSuffix(FieldTableName, v))
}

// TableNameEqualFold applies the EqualFold predicate on the "table_name" field.
func TableNameEqualFold(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEqualFold(FieldTableName, v))
}

// TableNameContainsFold applies the ContainsFold predicate on the "table_name" field.
func TableNameContainsFold(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldContainsFold(FieldTableName, v))
}

// SensitivityLevelEQ applies the EQ predicate on the "sensitivity_level" field.
func SensitivityLevelEQ(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldSensitivityLevel, v))
}

// SensitivityLevelNEQ applies the NEQ predicate on the "sensitivity_level" field.
func SensitivityLevelNEQ(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldSensitivityLevel, v))
}

// SensitivityLevelIn applies the In predicate on the "sensitivity_level" field.
func SensitivityLevelIn(vs ...string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldSensitivityLevel, vs...))
}

// SensitivityLevelNotIn applies the NotIn predicate on the "sensitivity_level" field.
func SensitivityLevelNotIn(vs ...string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldSensitivityLevel, vs...))
}

// SensitivityLevelGT applies the GT predicate on the "sensitivity_level" field.
func SensitivityLevelGT(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldSensitivityLevel, v))
}

// SensitivityLevelGTE applies the GTE predicate on the "sensitivity_level" field.
func SensitivityLevelGTE(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldSensitivityLevel, v))
}

// SensitivityLevelLT applies the LT predicate on the "sensitivity_level" field.
func SensitivityLevelLT(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldSensitivityLevel, v))
}

// SensitivityLevelLTE applies the LTE predicate on the "sensitivity_level" field.
func SensitivityLevelLTE(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldSensitivityLevel, v))
}

// SensitivityLevelContains applies the Contains predicate on the "sensitivity_level" field.
func SensitivityLevelContains(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldContains(FieldSensitivityLevel, v))
}

// SensitivityLevelHasPrefix applies the HasPrefix predicate on the "sensitivity_level" field.
func SensitivityLevelHasPrefix(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldHasPrefix(FieldSensitivityLevel, v))
}

// SensitivityLevelHasSuffix applies the HasSuffix predicate on the "sensitivity_level" field.
func SensitivityLevelHasSuffix(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldHasSuffix(FieldSensitivityLevel, v))
}

// SensitivityLevelEqualFold applies the EqualFold predicate on the "sensitivity_level" field.
func SensitivityLevelEqualFold(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEqualFold(FieldSensitivityLevel, v))
}

// SensitivityLevelContainsFold applies the ContainsFold predicate on the "sensitivity_level" field.
func SensitivityLevelContainsFold(v string) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldContainsFold(FieldSensitivityLevel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SensitiveTable) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SensitiveTable) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SensitiveTable) predicate.SensitiveTable {
	return predicate.SensitiveTable(sql.NotPredicates(p))
}
