// Code generated by ent, DO NOT EDIT.

package sharedresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharedresult type in the database.
	Label = "shared_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldColumnsJSON holds the string denoting the columns_json field in the database.
	FieldColumnsJSON = "columns_json"
	// FieldRowsJSON holds the string denoting the rows_json field in the database.
	FieldRowsJSON = "rows_json"
	// FieldRowCount holds the string denoting the row_count field in the database.
	FieldRowCount = "row_count"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldSQLSummary holds the string denoting the sql_summary field in the database.
	FieldSQLSummary = "sql_summary"
	// FieldDatasourceName holds the string denoting the datasource_name field in the database.
	FieldDatasourceName = "datasource_name"
	// FieldRevoked holds the string denoting the revoked field in the database.
	FieldRevoked = "revoked"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the sharedresult in the database.
	Table = "shared_results"
)

// Columns holds all SQL columns for sharedresult fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUsername,
	FieldToken,
	FieldColumnsJSON,
	FieldRowsJSON,
	FieldRowCount,
	FieldExpiresAt,
	FieldPasswordHash,
	FieldSQLSummary,
	FieldDatasourceName,
	FieldRevoked,
	FieldRevokedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// DefaultColumnsJSON holds the default value on creation for the "columns_json" field.
	DefaultColumnsJSON string
	// DefaultRowsJSON holds the default value on creation for the "rows_json" field.
	DefaultRowsJSON string
	// DefaultRowCount holds the default value on creation for the "row_count" field.
	DefaultRowCount int64
	// DefaultPasswordHash holds the default value on creation for the "password_hash" field.
	DefaultPasswordHash string
	// DefaultSQLSummary holds the default value on creation for the "sql_summary" field.
	DefaultSQLSummary string
	// DefaultDatasourceName holds the default value on creation for the "datasource_name" field.
	DefaultDatasourceName string
	// DefaultRevoked holds the default value on creation for the "revoked" field.
	DefaultRevoked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SharedResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByColumnsJSON orders the results by the columns_json field.
func ByColumnsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColumnsJSON, opts...).ToFunc()
}

// ByRowsJSON orders the results by the rows_json field.
func ByRowsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowsJSON, opts...).ToFunc()
}

// ByRowCount orders the results by the row_count field.
func ByRowCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowCount, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// BySQLSummary orders the results by the sql_summary field.
func BySQLSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSQLSummary, opts...).ToFunc()
}

// ByDatasourceName orders the results by the datasource_name field.
func ByDatasourceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDatasourceName, opts...).ToFunc()
}

// ByRevoked orders the results by the revoked field.
func ByRevoked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevoked, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
