// Code generated by ent, DO NOT EDIT.

package sharedresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldUserID, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldUsername, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldToken, v))
}

// ColumnsJSON applies equality check predicate on the "columns_json" field. It's identical to ColumnsJSONEQ.
func ColumnsJSON(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldColumnsJSON, v))
}

// RowsJSON applies equality check predicate on the "rows_json" field. It's identical to RowsJSONEQ.
func RowsJSON(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRowsJSON, v))
}

// RowCount applies equality check predicate on the "row_count" field. It's identical to RowCountEQ.
func RowCount(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRowCount, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldExpiresAt, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldPasswordHash, v))
}

// SQLSummary applies equality check predicate on the "sql_summary" field. It's identical to SQLSummaryEQ.
func SQLSummary(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldSQLSummary, v))
}

// DatasourceName applies equality check predicate on the "datasource_name" field. It's identical to DatasourceNameEQ.
func DatasourceName(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldDatasourceName, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRevoked, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldUserID, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldUsername, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldToken, v))
}

// ColumnsJSONEQ applies the EQ predicate on the "columns_json" field.
func ColumnsJSONEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldColumnsJSON, v))
}

// ColumnsJSONNEQ applies the NEQ predicate on the "columns_json" field.
func ColumnsJSONNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldColumnsJSON, v))
}

// ColumnsJSONIn applies the In predicate on the "columns_json" field.
func ColumnsJSONIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldColumnsJSON, vs...))
}

// ColumnsJSONNotIn applies the NotIn predicate on the "columns_json" field.
func ColumnsJSONNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldColumnsJSON, vs...))
}

// ColumnsJSONGT applies the GT predicate on the "columns_json" field.
func ColumnsJSONGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldColumnsJSON, v))
}

// ColumnsJSONGTE applies the GTE predicate on the "columns_json" field.
func ColumnsJSONGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldColumnsJSON, v))
}

// ColumnsJSONLT applies the LT predicate on the "columns_json" field.
func ColumnsJSONLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldColumnsJSON, v))
}

// ColumnsJSONLTE applies the LTE predicate on the "columns_json" field.
func ColumnsJSONLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldColumnsJSON, v))
}

// ColumnsJSONContains applies the Contains predicate on the "columns_json" field.
func ColumnsJSONContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldColumnsJSON, v))
}

// ColumnsJSONHasPrefix applies the HasPrefix predicate on the "columns_json" field.
func ColumnsJSONHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldColumnsJSON, v))
}

// ColumnsJSONHasSuffix applies the HasSuffix predicate on the "columns_json" field.
func ColumnsJSONHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldColumnsJSON, v))
}

// ColumnsJSONEqualFold applies the EqualFold predicate on the "columns_json" field.
func ColumnsJSONEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldColumnsJSON, v))
}

// ColumnsJSONContainsFold applies the ContainsFold predicate on the "columns_json" field.
func ColumnsJSONContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldColumnsJSON, v))
}

// RowsJSONEQ applies the EQ predicate on the "rows_json" field.
func RowsJSONEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRowsJSON, v))
}

// RowsJSONNEQ applies the NEQ predicate on the "rows_json" field.
func RowsJSONNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldRowsJSON, v))
}

// RowsJSONIn applies the In predicate on the "rows_json" field.
func RowsJSONIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldRowsJSON, vs...))
}

// RowsJSONNotIn applies the NotIn predicate on the "rows_json" field.
func RowsJSONNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldRowsJSON, vs...))
}

// RowsJSONGT applies the GT predicate on the "rows_json" field.
func RowsJSONGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldRowsJSON, v))
}

// RowsJSONGTE applies the GTE predicate on the "rows_json" field.
func RowsJSONGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldRowsJSON, v))
}

// RowsJSONLT applies the LT predicate on the "rows_json" field.
func RowsJSONLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldRowsJSON, v))
}

// RowsJSONLTE applies the LTE predicate on the "rows_json" field.
func RowsJSONLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldRowsJSON, v))
}

// RowsJSONContains applies the Contains predicate on the "rows_json" field.
func RowsJSONContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldRowsJSON, v))
}

// RowsJSONHasPrefix applies the HasPrefix predicate on the "rows_json" field.
func RowsJSONHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldRowsJSON, v))
}

// RowsJSONHasSuffix applies the HasSuffix predicate on the "rows_json" field.
func RowsJSONHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldRowsJSON, v))
}

// RowsJSONEqualFold applies the EqualFold predicate on the "rows_json" field.
func RowsJSONEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldRowsJSON, v))
}

// RowsJSONContainsFold applies the ContainsFold predicate on the "rows_json" field.
func RowsJSONContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldRowsJSON, v))
}

// RowCountEQ applies the EQ predicate on the "row_count" field.
func RowCountEQ(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRowCount, v))
}

// RowCountNEQ applies the NEQ predicate on the "row_count" field.
func RowCountNEQ(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldRowCount, v))
}

// RowCountIn applies the In predicate on the "row_count" field.
func RowCountIn(vs ...int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldRowCount, vs...))
}

// RowCountNotIn applies the NotIn predicate on the "row_count" field.
func RowCountNotIn(vs ...int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldRowCount, vs...))
}

// RowCountGT applies the GT predicate on the "row_count" field.
func RowCountGT(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldRowCount, v))
}

// RowCountGTE applies the GTE predicate on the "row_count" field.
func RowCountGTE(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldRowCount, v))
}

// RowCountLT applies the LT predicate on the "row_count" field.
func RowCountLT(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldRowCount, v))
}

// RowCountLTE applies the LTE predicate on the "row_count" field.
func RowCountLTE(v int64) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldRowCount, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldExpiresAt, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldPasswordHash, v))
}

// SQLSummaryEQ applies the EQ predicate on the "sql_summary" field.
func SQLSummaryEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldSQLSummary, v))
}

// SQLSummaryNEQ applies the NEQ predicate on the "sql_summary" field.
func SQLSummaryNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldSQLSummary, v))
}

// SQLSummaryIn applies the In predicate on the "sql_summary" field.
func SQLSummaryIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldSQLSummary, vs...))
}

// SQLSummaryNotIn applies the NotIn predicate on the "sql_summary" field.
func SQLSummaryNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldSQLSummary, vs...))
}

// SQLSummaryGT applies the GT predicate on the "sql_summary" field.
func SQLSummaryGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldSQLSummary, v))
}

// SQLSummaryGTE applies the GTE predicate on the "sql_summary" field.
func SQLSummaryGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldSQLSummary, v))
}

// SQLSummaryLT applies the LT predicate on the "sql_summary" field.
func SQLSummaryLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldSQLSummary, v))
}

// SQLSummaryLTE applies the LTE predicate on the "sql_summary" field.
func SQLSummaryLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldSQLSummary, v))
}

// SQLSummaryContains applies the Contains predicate on the "sql_summary" field.
func SQLSummaryContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldSQLSummary, v))
}

// SQLSummaryHasPrefix applies the HasPrefix predicate on the "sql_summary" field.
func SQLSummaryHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldSQLSummary, v))
}

// SQLSummaryHasSuffix applies the HasSuffix predicate on the "sql_summary" field.
func SQLSummaryHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldSQLSummary, v))
}

// SQLSummaryEqualFold applies the EqualFold predicate on the "sql_summary" field.
func SQLSummaryEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldSQLSummary, v))
}

// SQLSummaryContainsFold applies the ContainsFold predicate on the "sql_summary" field.
func SQLSummaryContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldSQLSummary, v))
}

// DatasourceNameEQ applies the EQ predicate on the "datasource_name" field.
func DatasourceNameEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldDatasourceName, v))
}

// DatasourceNameNEQ applies the NEQ predicate on the "datasource_name" field.
func DatasourceNameNEQ(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldDatasourceName, v))
}

// DatasourceNameIn applies the In predicate on the "datasource_name" field.
func DatasourceNameIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldDatasourceName, vs...))
}

// DatasourceNameNotIn applies the NotIn predicate on the "datasource_name" field.
func DatasourceNameNotIn(vs ...string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldDatasourceName, vs...))
}

// DatasourceNameGT applies the GT predicate on the "datasource_name" field.
func DatasourceNameGT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldDatasourceName, v))
}

// DatasourceNameGTE applies the GTE predicate on the "datasource_name" field.
func DatasourceNameGTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldDatasourceName, v))
}

// DatasourceNameLT applies the LT predicate on the "datasource_name" field.
func DatasourceNameLT(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldDatasourceName, v))
}

// DatasourceNameLTE applies the LTE predicate on the "datasource_name" field.
func DatasourceNameLTE(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldDatasourceName, v))
}

// DatasourceNameContains applies the Contains predicate on the "datasource_name" field.
func DatasourceNameContains(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContains(FieldDatasourceName, v))
}

// DatasourceNameHasPrefix applies the HasPrefix predicate on the "datasource_name" field.
func DatasourceNameHasPrefix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasPrefix(FieldDatasourceName, v))
}

// DatasourceNameHasSuffix applies the HasSuffix predicate on the "datasource_name" field.
func DatasourceNameHasSuffix(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldHasSuffix(FieldDatasourceName, v))
}

// DatasourceNameEqualFold applies the EqualFold predicate on the "datasource_name" field.
func DatasourceNameEqualFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEqualFold(FieldDatasourceName, v))
}

// DatasourceNameContainsFold applies the ContainsFold predicate on the "datasource_name" field.
func DatasourceNameContainsFold(v string) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldContainsFold(FieldDatasourceName, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldRevoked, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotNull(FieldRevokedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SharedResult {
	return predicate.SharedResult(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedResult) predicate.SharedResult {
	return predicate.SharedResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedResult) predicate.SharedResult {
	return predicate.SharedResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedResult) predicate.SharedResult {
	return predicate.SharedResult(sql.NotPredicates(p))
}
