// Code generated by ent, DO NOT EDIT.

package webhooksubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldURL, v))
}

// EncryptedSecret applies equality check predicate on the "encrypted_secret" field. It's identical to EncryptedSecretEQ.
func EncryptedSecret(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldEncryptedSecret, v))
}

// Events applies equality check predicate on the "events" field. It's identical to EventsEQ.
func Events(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldEvents, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldEnabled, v))
}

// FailureCount applies equality check predicate on the "failure_count" field. It's identical to FailureCountEQ.
func FailureCount(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldFailureCount, v))
}

// LastTriggeredAt applies equality check predicate on the "last_triggered_at" field. It's identical to LastTriggeredAtEQ.
func LastTriggeredAt(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldLastTriggeredAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldName, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldURL, v))
}

// EncryptedSecretEQ applies the EQ predicate on the "encrypted_secret" field.
func EncryptedSecretEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldEncryptedSecret, v))
}

// EncryptedSecretNEQ applies the NEQ predicate on the "encrypted_secret" field.
func EncryptedSecretNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldEncryptedSecret, v))
}

// EncryptedSecretIn applies the In predicate on the "encrypted_secret" field.
func EncryptedSecretIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldEncryptedSecret, vs...))
}

// EncryptedSecretNotIn applies the NotIn predicate on the "encrypted_secret" field.
func EncryptedSecretNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldEncryptedSecret, vs...))
}

// EncryptedSecretGT applies the GT predicate on the "encrypted_secret" field.
func EncryptedSecretGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldEncryptedSecret, v))
}

// EncryptedSecretGTE applies the GTE predicate on the "encrypted_secret" field.
func EncryptedSecretGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldEncryptedSecret, v))
}

// EncryptedSecretLT applies the LT predicate on the "encrypted_secret" field.
func EncryptedSecretLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldEncryptedSecret, v))
}

// EncryptedSecretLTE applies the LTE predicate on the "encrypted_secret" field.
func EncryptedSecretLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldEncryptedSecret, v))
}

// EncryptedSecretContains applies the Contains predicate on the "encrypted_secret" field.
func EncryptedSecretContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldEncryptedSecret, v))
}

// EncryptedSecretHasPrefix applies the HasPrefix predicate on the "encrypted_secret" field.
func EncryptedSecretHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldEncryptedSecret, v))
}

// EncryptedSecretHasSuffix applies the HasSuffix predicate on the "encrypted_secret" field.
func EncryptedSecretHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldEncryptedSecret, v))
}

// EncryptedSecretEqualFold applies the EqualFold predicate on the "encrypted_secret" field.
func EncryptedSecretEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldEncryptedSecret, v))
}

// EncryptedSecretContainsFold applies the ContainsFold predicate on the "encrypted_secret" field.
func EncryptedSecretContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldEncryptedSecret, v))
}

// EventsEQ applies the EQ predicate on the "events" field.
func EventsEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldEvents, v))
}

// EventsNEQ applies the NEQ predicate on the "events" field.
func EventsNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldEvents, v))
}

// EventsIn applies the In predicate on the "events" field.
func EventsIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldEvents, vs...))
}

// EventsNotIn applies the NotIn predicate on the "events" field.
func EventsNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldEvents, vs...))
}

// EventsGT applies the GT predicate on the "events" field.
func EventsGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldEvents, v))
}

// EventsGTE applies the GTE predicate on the "events" field.
func EventsGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldEvents, v))
}

// EventsLT applies the LT predicate on the "events" field.
func EventsLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldEvents, v))
}

// EventsLTE applies the LTE predicate on the "events" field.
func EventsLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldEvents, v))
}

// EventsContains applies the Contains predicate on the "events" field.
func EventsContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldEvents, v))
}

// EventsHasPrefix applies the HasPrefix predicate on the "events" field.
func EventsHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldEvents, v))
}

// EventsHasSuffix applies the HasSuffix predicate on the "events" field.
func EventsHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldEvents, v))
}

// EventsEqualFold applies the EqualFold predicate on the "events" field.
func EventsEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldEvents, v))
}

// EventsContainsFold applies the ContainsFold predicate on the "events" field.
func EventsContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldEvents, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldEnabled, v))
}

// FailureCountEQ applies the EQ predicate on the "failure_count" field.
func FailureCountEQ(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldFailureCount, v))
}

// FailureCountNEQ applies the NEQ predicate on the "failure_count" field.
func FailureCountNEQ(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldFailureCount, v))
}

// FailureCountIn applies the In predicate on the "failure_count" field.
func FailureCountIn(vs ...int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldFailureCount, vs...))
}

// FailureCountNotIn applies the NotIn predicate on the "failure_count" field.
func FailureCountNotIn(vs ...int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldFailureCount, vs...))
}

// FailureCountGT applies the GT predicate on the "failure_count" field.
func FailureCountGT(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldFailureCount, v))
}

// FailureCountGTE applies the GTE predicate on the "failure_count" field.
func FailureCountGTE(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldFailureCount, v))
}

// FailureCountLT applies the LT predicate on the "failure_count" field.
func FailureCountLT(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldFailureCount, v))
}

// FailureCountLTE applies the LTE predicate on the "failure_count" field.
func FailureCountLTE(v int64) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldFailureCount, v))
}

// LastTriggeredAtEQ applies the EQ predicate on the "last_triggered_at" field.
func LastTriggeredAtEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldLastTriggeredAt, v))
}

// LastTriggeredAtNEQ applies the NEQ predicate on the "last_triggered_at" field.
func LastTriggeredAtNEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldLastTriggeredAt, v))
}

// LastTriggeredAtIn applies the In predicate on the "last_triggered_at" field.
func LastTriggeredAtIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldLastTriggeredAt, vs...))
}

// LastTriggeredAtNotIn applies the NotIn predicate on the "last_triggered_at" field.
func LastTriggeredAtNotIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldLastTriggeredAt, vs...))
}

// LastTriggeredAtGT applies the GT predicate on the "last_triggered_at" field.
func LastTriggeredAtGT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldLastTriggeredAt, v))
}

// LastTriggeredAtGTE applies the GTE predicate on the "last_triggered_at" field.
func LastTriggeredAtGTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldLastTriggeredAt, v))
}

// LastTriggeredAtLT applies the LT predicate on the "last_triggered_at" field.
func LastTriggeredAtLT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldLastTriggeredAt, v))
}

// LastTriggeredAtLTE applies the LTE predicate on the "last_triggered_at" field.
func LastTriggeredAtLTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldLastTriggeredAt, v))
}

// LastTriggeredAtIsNil applies the IsNil predicate on the "last_triggered_at" field.
func LastTriggeredAtIsNil() predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIsNull(FieldLastTriggeredAt))
}

// LastTriggeredAtNotNil applies the NotNil predicate on the "last_triggered_at" field.
func LastTriggeredAtNotNil() predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotNull(FieldLastTriggeredAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebhookSubscription) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebhookSubscription) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebhookSubscription) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.NotPredicates(p))
}
