// Code generated by ent, DO NOT EDIT.

package exporttask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the exporttask type in the database.
	Label = "export_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldExportType holds the string denoting the export_type field in the database.
	FieldExportType = "export_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFileFormat holds the string denoting the file_format field in the database.
	FieldFileFormat = "file_format"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldFilePath holds the string denoting the file_path field in the database.
	FieldFilePath = "file_path"
	// FieldTotalRows holds the string denoting the total_rows field in the database.
	FieldTotalRows = "total_rows"
	// FieldFileBytes holds the string denoting the file_bytes field in the database.
	FieldFileBytes = "file_bytes"
	// FieldFiltersJSON holds the string denoting the filters_json field in the database.
	FieldFiltersJSON = "filters_json"
	// FieldErrorMsg holds the string denoting the error_msg field in the database.
	FieldErrorMsg = "error_msg"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the exporttask in the database.
	Table = "export_tasks"
)

// Columns holds all SQL columns for exporttask fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUsername,
	FieldExportType,
	FieldStatus,
	FieldFileFormat,
	FieldFilename,
	FieldFilePath,
	FieldTotalRows,
	FieldFileBytes,
	FieldFiltersJSON,
	FieldErrorMsg,
	FieldCreatedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultExportType holds the default value on creation for the "export_type" field.
	DefaultExportType string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultFileFormat holds the default value on creation for the "file_format" field.
	DefaultFileFormat string
	// DefaultFilename holds the default value on creation for the "filename" field.
	DefaultFilename string
	// DefaultFilePath holds the default value on creation for the "file_path" field.
	DefaultFilePath string
	// DefaultTotalRows holds the default value on creation for the "total_rows" field.
	DefaultTotalRows int64
	// DefaultFileBytes holds the default value on creation for the "file_bytes" field.
	DefaultFileBytes int64
	// DefaultFiltersJSON holds the default value on creation for the "filters_json" field.
	DefaultFiltersJSON string
	// DefaultErrorMsg holds the default value on creation for the "error_msg" field.
	DefaultErrorMsg string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ExportTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByExportType orders the results by the export_type field.
func ByExportType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFileFormat orders the results by the file_format field.
func ByFileFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileFormat, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// ByFilePath orders the results by the file_path field.
func ByFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilePath, opts...).ToFunc()
}

// ByTotalRows orders the results by the total_rows field.
func ByTotalRows(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRows, opts...).ToFunc()
}

// ByFileBytes orders the results by the file_bytes field.
func ByFileBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileBytes, opts...).ToFunc()
}

// ByFiltersJSON orders the results by the filters_json field.
func ByFiltersJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFiltersJSON, opts...).ToFunc()
}

// ByErrorMsg orders the results by the error_msg field.
func ByErrorMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMsg, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
