// Code generated by ent, DO NOT EDIT.

package querysnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the querysnapshot type in the database.
	Label = "query_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldColumnsJSON holds the string denoting the columns_json field in the database.
	FieldColumnsJSON = "columns"
	// FieldRowsJSON holds the string denoting the rows_json field in the database.
	FieldRowsJSON = "rows"
	// FieldRowCount holds the string denoting the row_count field in the database.
	FieldRowCount = "row_count"
	// FieldQueryHistoryID holds the string denoting the query_history_id field in the database.
	FieldQueryHistoryID = "query_history_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the querysnapshot in the database.
	Table = "query_snapshots"
)

// Columns holds all SQL columns for querysnapshot fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldLabel,
	FieldColumnsJSON,
	FieldRowsJSON,
	FieldRowCount,
	FieldQueryHistoryID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// ColumnsJSONValidator is a validator for the "columns_json" field. It is called by the builders before save.
	ColumnsJSONValidator func(string) error
	// RowsJSONValidator is a validator for the "rows_json" field. It is called by the builders before save.
	RowsJSONValidator func(string) error
	// DefaultRowCount holds the default value on creation for the "row_count" field.
	DefaultRowCount int64
	// DefaultQueryHistoryID holds the default value on creation for the "query_history_id" field.
	DefaultQueryHistoryID int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the QuerySnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByColumnsJSON orders the results by the columns_json field.
func ByColumnsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColumnsJSON, opts...).ToFunc()
}

// ByRowsJSON orders the results by the rows_json field.
func ByRowsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowsJSON, opts...).ToFunc()
}

// ByRowCount orders the results by the row_count field.
func ByRowCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowCount, opts...).ToFunc()
}

// ByQueryHistoryID orders the results by the query_history_id field.
func ByQueryHistoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQueryHistoryID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
