// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/exporttask"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
)

// ExportTaskUpdate is the builder for updating ExportTask entities.
type ExportTaskUpdate struct {
	config
	hooks    []Hook
	mutation *ExportTaskMutation
}

// Where appends a list predicates to the ExportTaskUpdate builder.
func (_u *ExportTaskUpdate) Where(ps ...predicate.ExportTask) *ExportTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExportTaskUpdate) SetUserID(v int64) *ExportTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableUserID(v *int64) *ExportTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ExportTaskUpdate) AddUserID(v int64) *ExportTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *ExportTaskUpdate) SetUsername(v string) *ExportTaskUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableUsername(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExportType sets the "export_type" field.
func (_u *ExportTaskUpdate) SetExportType(v string) *ExportTaskUpdate {
	_u.mutation.SetExportType(v)
	return _u
}

// SetNillableExportType sets the "export_type" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableExportType(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetExportType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExportTaskUpdate) SetStatus(v string) *ExportTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableStatus(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *ExportTaskUpdate) SetFilename(v string) *ExportTaskUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableFilename(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ExportTaskUpdate) SetFilePath(v string) *ExportTaskUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableFilePath(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetTotalRows sets the "total_rows" field.
func (_u *ExportTaskUpdate) SetTotalRows(v int64) *ExportTaskUpdate {
	_u.mutation.ResetTotalRows()
	_u.mutation.SetTotalRows(v)
	return _u
}

// SetNillableTotalRows sets the "total_rows" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableTotalRows(v *int64) *ExportTaskUpdate {
	if v != nil {
		_u.SetTotalRows(*v)
	}
	return _u
}

// AddTotalRows adds value to the "total_rows" field.
func (_u *ExportTaskUpdate) AddTotalRows(v int64) *ExportTaskUpdate {
	_u.mutation.AddTotalRows(v)
	return _u
}

// SetFileBytes sets the "file_bytes" field.
func (_u *ExportTaskUpdate) SetFileBytes(v int64) *ExportTaskUpdate {
	_u.mutation.ResetFileBytes()
	_u.mutation.SetFileBytes(v)
	return _u
}

// SetNillableFileBytes sets the "file_bytes" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableFileBytes(v *int64) *ExportTaskUpdate {
	if v != nil {
		_u.SetFileBytes(*v)
	}
	return _u
}

// AddFileBytes adds value to the "file_bytes" field.
func (_u *ExportTaskUpdate) AddFileBytes(v int64) *ExportTaskUpdate {
	_u.mutation.AddFileBytes(v)
	return _u
}

// SetFiltersJSON sets the "filters_json" field.
func (_u *ExportTaskUpdate) SetFiltersJSON(v string) *ExportTaskUpdate {
	_u.mutation.SetFiltersJSON(v)
	return _u
}

// SetNillableFiltersJSON sets the "filters_json" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableFiltersJSON(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetFiltersJSON(*v)
	}
	return _u
}

// SetErrorMsg sets the "error_msg" field.
func (_u *ExportTaskUpdate) SetErrorMsg(v string) *ExportTaskUpdate {
	_u.mutation.SetErrorMsg(v)
	return _u
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableErrorMsg(v *string) *ExportTaskUpdate {
	if v != nil {
		_u.SetErrorMsg(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ExportTaskUpdate) SetCreatedAt(v time.Time) *ExportTaskUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableCreatedAt(v *time.Time) *ExportTaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ExportTaskUpdate) SetCompletedAt(v time.Time) *ExportTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ExportTaskUpdate) SetNillableCompletedAt(v *time.Time) *ExportTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ExportTaskUpdate) ClearCompletedAt() *ExportTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ExportTaskMutation object of the builder.
func (_u *ExportTaskUpdate) Mutation() *ExportTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExportTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExportTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExportTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExportTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ExportTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(exporttask.Table, exporttask.Columns, sqlgraph.NewFieldSpec(exporttask.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(exporttask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(exporttask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(exporttask.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExportType(); ok {
		_spec.SetField(exporttask.FieldExportType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(exporttask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(exporttask.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(exporttask.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalRows(); ok {
		_spec.SetField(exporttask.FieldTotalRows, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRows(); ok {
		_spec.AddField(exporttask.FieldTotalRows, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileBytes(); ok {
		_spec.SetField(exporttask.FieldFileBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileBytes(); ok {
		_spec.AddField(exporttask.FieldFileBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FiltersJSON(); ok {
		_spec.SetField(exporttask.FieldFiltersJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMsg(); ok {
		_spec.SetField(exporttask.FieldErrorMsg, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(exporttask.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(exporttask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(exporttask.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exporttask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExportTaskUpdateOne is the builder for updating a single ExportTask entity.
type ExportTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExportTaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *ExportTaskUpdateOne) SetUserID(v int64) *ExportTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableUserID(v *int64) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ExportTaskUpdateOne) AddUserID(v int64) *ExportTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *ExportTaskUpdateOne) SetUsername(v string) *ExportTaskUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableUsername(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExportType sets the "export_type" field.
func (_u *ExportTaskUpdateOne) SetExportType(v string) *ExportTaskUpdateOne {
	_u.mutation.SetExportType(v)
	return _u
}

// SetNillableExportType sets the "export_type" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableExportType(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetExportType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExportTaskUpdateOne) SetStatus(v string) *ExportTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableStatus(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *ExportTaskUpdateOne) SetFilename(v string) *ExportTaskUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableFilename(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ExportTaskUpdateOne) SetFilePath(v string) *ExportTaskUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableFilePath(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetTotalRows sets the "total_rows" field.
func (_u *ExportTaskUpdateOne) SetTotalRows(v int64) *ExportTaskUpdateOne {
	_u.mutation.ResetTotalRows()
	_u.mutation.SetTotalRows(v)
	return _u
}

// SetNillableTotalRows sets the "total_rows" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableTotalRows(v *int64) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetTotalRows(*v)
	}
	return _u
}

// AddTotalRows adds value to the "total_rows" field.
func (_u *ExportTaskUpdateOne) AddTotalRows(v int64) *ExportTaskUpdateOne {
	_u.mutation.AddTotalRows(v)
	return _u
}

// SetFileBytes sets the "file_bytes" field.
func (_u *ExportTaskUpdateOne) SetFileBytes(v int64) *ExportTaskUpdateOne {
	_u.mutation.ResetFileBytes()
	_u.mutation.SetFileBytes(v)
	return _u
}

// SetNillableFileBytes sets the "file_bytes" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableFileBytes(v *int64) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetFileBytes(*v)
	}
	return _u
}

// AddFileBytes adds value to the "file_bytes" field.
func (_u *ExportTaskUpdateOne) AddFileBytes(v int64) *ExportTaskUpdateOne {
	_u.mutation.AddFileBytes(v)
	return _u
}

// SetFiltersJSON sets the "filters_json" field.
func (_u *ExportTaskUpdateOne) SetFiltersJSON(v string) *ExportTaskUpdateOne {
	_u.mutation.SetFiltersJSON(v)
	return _u
}

// SetNillableFiltersJSON sets the "filters_json" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableFiltersJSON(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetFiltersJSON(*v)
	}
	return _u
}

// SetErrorMsg sets the "error_msg" field.
func (_u *ExportTaskUpdateOne) SetErrorMsg(v string) *ExportTaskUpdateOne {
	_u.mutation.SetErrorMsg(v)
	return _u
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableErrorMsg(v *string) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetErrorMsg(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ExportTaskUpdateOne) SetCreatedAt(v time.Time) *ExportTaskUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableCreatedAt(v *time.Time) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ExportTaskUpdateOne) SetCompletedAt(v time.Time) *ExportTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ExportTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *ExportTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ExportTaskUpdateOne) ClearCompletedAt() *ExportTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ExportTaskMutation object of the builder.
func (_u *ExportTaskUpdateOne) Mutation() *ExportTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExportTaskUpdate builder.
func (_u *ExportTaskUpdateOne) Where(ps ...predicate.ExportTask) *ExportTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExportTaskUpdateOne) Select(field string, fields ...string) *ExportTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExportTask entity.
func (_u *ExportTaskUpdateOne) Save(ctx context.Context) (*ExportTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExportTaskUpdateOne) SaveX(ctx context.Context) *ExportTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExportTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExportTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ExportTaskUpdateOne) sqlSave(ctx context.Context) (_node *ExportTask, err error) {
	_spec := sqlgraph.NewUpdateSpec(exporttask.Table, exporttask.Columns, sqlgraph.NewFieldSpec(exporttask.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExportTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exporttask.FieldID)
		for _, f := range fields {
			if !exporttask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exporttask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(exporttask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(exporttask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(exporttask.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExportType(); ok {
		_spec.SetField(exporttask.FieldExportType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(exporttask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(exporttask.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(exporttask.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalRows(); ok {
		_spec.SetField(exporttask.FieldTotalRows, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRows(); ok {
		_spec.AddField(exporttask.FieldTotalRows, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileBytes(); ok {
		_spec.SetField(exporttask.FieldFileBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileBytes(); ok {
		_spec.AddField(exporttask.FieldFileBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FiltersJSON(); ok {
		_spec.SetField(exporttask.FieldFiltersJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMsg(); ok {
		_spec.SetField(exporttask.FieldErrorMsg, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(exporttask.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(exporttask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(exporttask.FieldCompletedAt, field.TypeTime)
	}
	_node = &ExportTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exporttask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
