// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/exporttask"
)

// ExportTaskCreate is the builder for creating a ExportTask entity.
type ExportTaskCreate struct {
	config
	mutation *ExportTaskMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ExportTaskCreate) SetUserID(v int64) *ExportTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *ExportTaskCreate) SetUsername(v string) *ExportTaskCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableUsername(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetExportType sets the "export_type" field.
func (_c *ExportTaskCreate) SetExportType(v string) *ExportTaskCreate {
	_c.mutation.SetExportType(v)
	return _c
}

// SetNillableExportType sets the "export_type" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableExportType(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetExportType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExportTaskCreate) SetStatus(v string) *ExportTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableStatus(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFilename sets the "filename" field.
func (_c *ExportTaskCreate) SetFilename(v string) *ExportTaskCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableFilename(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetFilename(*v)
	}
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *ExportTaskCreate) SetFilePath(v string) *ExportTaskCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableFilePath(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetFilePath(*v)
	}
	return _c
}

// SetTotalRows sets the "total_rows" field.
func (_c *ExportTaskCreate) SetTotalRows(v int64) *ExportTaskCreate {
	_c.mutation.SetTotalRows(v)
	return _c
}

// SetNillableTotalRows sets the "total_rows" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableTotalRows(v *int64) *ExportTaskCreate {
	if v != nil {
		_c.SetTotalRows(*v)
	}
	return _c
}

// SetFileBytes sets the "file_bytes" field.
func (_c *ExportTaskCreate) SetFileBytes(v int64) *ExportTaskCreate {
	_c.mutation.SetFileBytes(v)
	return _c
}

// SetNillableFileBytes sets the "file_bytes" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableFileBytes(v *int64) *ExportTaskCreate {
	if v != nil {
		_c.SetFileBytes(*v)
	}
	return _c
}

// SetFiltersJSON sets the "filters_json" field.
func (_c *ExportTaskCreate) SetFiltersJSON(v string) *ExportTaskCreate {
	_c.mutation.SetFiltersJSON(v)
	return _c
}

// SetNillableFiltersJSON sets the "filters_json" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableFiltersJSON(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetFiltersJSON(*v)
	}
	return _c
}

// SetErrorMsg sets the "error_msg" field.
func (_c *ExportTaskCreate) SetErrorMsg(v string) *ExportTaskCreate {
	_c.mutation.SetErrorMsg(v)
	return _c
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableErrorMsg(v *string) *ExportTaskCreate {
	if v != nil {
		_c.SetErrorMsg(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExportTaskCreate) SetCreatedAt(v time.Time) *ExportTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableCreatedAt(v *time.Time) *ExportTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ExportTaskCreate) SetCompletedAt(v time.Time) *ExportTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ExportTaskCreate) SetNillableCompletedAt(v *time.Time) *ExportTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// Mutation returns the ExportTaskMutation object of the builder.
func (_c *ExportTaskCreate) Mutation() *ExportTaskMutation {
	return _c.mutation
}

// Save creates the ExportTask in the database.
func (_c *ExportTaskCreate) Save(ctx context.Context) (*ExportTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExportTaskCreate) SaveX(ctx context.Context) *ExportTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExportTaskCreate) defaults() {
	if _, ok := _c.mutation.Username(); !ok {
		v := exporttask.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.ExportType(); !ok {
		v := exporttask.DefaultExportType
		_c.mutation.SetExportType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := exporttask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Filename(); !ok {
		v := exporttask.DefaultFilename
		_c.mutation.SetFilename(v)
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		v := exporttask.DefaultFilePath
		_c.mutation.SetFilePath(v)
	}
	if _, ok := _c.mutation.TotalRows(); !ok {
		v := exporttask.DefaultTotalRows
		_c.mutation.SetTotalRows(v)
	}
	if _, ok := _c.mutation.FileBytes(); !ok {
		v := exporttask.DefaultFileBytes
		_c.mutation.SetFileBytes(v)
	}
	if _, ok := _c.mutation.FiltersJSON(); !ok {
		v := exporttask.DefaultFiltersJSON
		_c.mutation.SetFiltersJSON(v)
	}
	if _, ok := _c.mutation.ErrorMsg(); !ok {
		v := exporttask.DefaultErrorMsg
		_c.mutation.SetErrorMsg(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := exporttask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExportTaskCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ExportTask.user_id"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "ExportTask.username"`)}
	}
	if _, ok := _c.mutation.ExportType(); !ok {
		return &ValidationError{Name: "export_type", err: errors.New(`ent: missing required field "ExportTask.export_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExportTask.status"`)}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "ExportTask.filename"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "ExportTask.file_path"`)}
	}
	if _, ok := _c.mutation.TotalRows(); !ok {
		return &ValidationError{Name: "total_rows", err: errors.New(`ent: missing required field "ExportTask.total_rows"`)}
	}
	if _, ok := _c.mutation.FileBytes(); !ok {
		return &ValidationError{Name: "file_bytes", err: errors.New(`ent: missing required field "ExportTask.file_bytes"`)}
	}
	if _, ok := _c.mutation.FiltersJSON(); !ok {
		return &ValidationError{Name: "filters_json", err: errors.New(`ent: missing required field "ExportTask.filters_json"`)}
	}
	if _, ok := _c.mutation.ErrorMsg(); !ok {
		return &ValidationError{Name: "error_msg", err: errors.New(`ent: missing required field "ExportTask.error_msg"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExportTask.created_at"`)}
	}
	return nil
}

func (_c *ExportTaskCreate) sqlSave(ctx context.Context) (*ExportTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExportTaskCreate) createSpec() (*ExportTask, *sqlgraph.CreateSpec) {
	var (
		_node = &ExportTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exporttask.Table, sqlgraph.NewFieldSpec(exporttask.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(exporttask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(exporttask.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.ExportType(); ok {
		_spec.SetField(exporttask.FieldExportType, field.TypeString, value)
		_node.ExportType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(exporttask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(exporttask.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(exporttask.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.TotalRows(); ok {
		_spec.SetField(exporttask.FieldTotalRows, field.TypeInt64, value)
		_node.TotalRows = value
	}
	if value, ok := _c.mutation.FileBytes(); ok {
		_spec.SetField(exporttask.FieldFileBytes, field.TypeInt64, value)
		_node.FileBytes = value
	}
	if value, ok := _c.mutation.FiltersJSON(); ok {
		_spec.SetField(exporttask.FieldFiltersJSON, field.TypeString, value)
		_node.FiltersJSON = value
	}
	if value, ok := _c.mutation.ErrorMsg(); ok {
		_spec.SetField(exporttask.FieldErrorMsg, field.TypeString, value)
		_node.ErrorMsg = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(exporttask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(exporttask.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// ExportTaskCreateBulk is the builder for creating many ExportTask entities in bulk.
type ExportTaskCreateBulk struct {
	config
	err      error
	builders []*ExportTaskCreate
}

// Save creates the ExportTask entities in the database.
func (_c *ExportTaskCreateBulk) Save(ctx context.Context) ([]*ExportTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExportTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExportTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExportTaskCreateBulk) SaveX(ctx context.Context) []*ExportTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
