// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/feishuwebhook"
)

// FeishuWebhookCreate is the builder for creating a FeishuWebhook entity.
type FeishuWebhookCreate struct {
	config
	mutation *FeishuWebhookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *FeishuWebhookCreate) SetName(v string) *FeishuWebhookCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEncryptedURL sets the "encrypted_url" field.
func (_c *FeishuWebhookCreate) SetEncryptedURL(v string) *FeishuWebhookCreate {
	_c.mutation.SetEncryptedURL(v)
	return _c
}

// SetURLHash sets the "url_hash" field.
func (_c *FeishuWebhookCreate) SetURLHash(v string) *FeishuWebhookCreate {
	_c.mutation.SetURLHash(v)
	return _c
}

// SetScene sets the "scene" field.
func (_c *FeishuWebhookCreate) SetScene(v string) *FeishuWebhookCreate {
	_c.mutation.SetScene(v)
	return _c
}

// SetNillableScene sets the "scene" field if the given value is not nil.
func (_c *FeishuWebhookCreate) SetNillableScene(v *string) *FeishuWebhookCreate {
	if v != nil {
		_c.SetScene(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *FeishuWebhookCreate) SetEnabled(v bool) *FeishuWebhookCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *FeishuWebhookCreate) SetNillableEnabled(v *bool) *FeishuWebhookCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRateLimitRps sets the "rate_limit_rps" field.
func (_c *FeishuWebhookCreate) SetRateLimitRps(v float64) *FeishuWebhookCreate {
	_c.mutation.SetRateLimitRps(v)
	return _c
}

// SetNillableRateLimitRps sets the "rate_limit_rps" field if the given value is not nil.
func (_c *FeishuWebhookCreate) SetNillableRateLimitRps(v *float64) *FeishuWebhookCreate {
	if v != nil {
		_c.SetRateLimitRps(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *FeishuWebhookCreate) SetCreatedBy(v string) *FeishuWebhookCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *FeishuWebhookCreate) SetNillableCreatedBy(v *string) *FeishuWebhookCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FeishuWebhookCreate) SetCreatedAt(v time.Time) *FeishuWebhookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FeishuWebhookCreate) SetNillableCreatedAt(v *time.Time) *FeishuWebhookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FeishuWebhookCreate) SetUpdatedAt(v time.Time) *FeishuWebhookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FeishuWebhookCreate) SetNillableUpdatedAt(v *time.Time) *FeishuWebhookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the FeishuWebhookMutation object of the builder.
func (_c *FeishuWebhookCreate) Mutation() *FeishuWebhookMutation {
	return _c.mutation
}

// Save creates the FeishuWebhook in the database.
func (_c *FeishuWebhookCreate) Save(ctx context.Context) (*FeishuWebhook, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FeishuWebhookCreate) SaveX(ctx context.Context) *FeishuWebhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeishuWebhookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeishuWebhookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FeishuWebhookCreate) defaults() {
	if _, ok := _c.mutation.Scene(); !ok {
		v := feishuwebhook.DefaultScene
		_c.mutation.SetScene(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := feishuwebhook.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.RateLimitRps(); !ok {
		v := feishuwebhook.DefaultRateLimitRps
		_c.mutation.SetRateLimitRps(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := feishuwebhook.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := feishuwebhook.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := feishuwebhook.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FeishuWebhookCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "FeishuWebhook.name"`)}
	}
	if _, ok := _c.mutation.EncryptedURL(); !ok {
		return &ValidationError{Name: "encrypted_url", err: errors.New(`ent: missing required field "FeishuWebhook.encrypted_url"`)}
	}
	if _, ok := _c.mutation.URLHash(); !ok {
		return &ValidationError{Name: "url_hash", err: errors.New(`ent: missing required field "FeishuWebhook.url_hash"`)}
	}
	if _, ok := _c.mutation.Scene(); !ok {
		return &ValidationError{Name: "scene", err: errors.New(`ent: missing required field "FeishuWebhook.scene"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "FeishuWebhook.enabled"`)}
	}
	if _, ok := _c.mutation.RateLimitRps(); !ok {
		return &ValidationError{Name: "rate_limit_rps", err: errors.New(`ent: missing required field "FeishuWebhook.rate_limit_rps"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "FeishuWebhook.created_by"`)}
	}
	return nil
}

func (_c *FeishuWebhookCreate) sqlSave(ctx context.Context) (*FeishuWebhook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FeishuWebhookCreate) createSpec() (*FeishuWebhook, *sqlgraph.CreateSpec) {
	var (
		_node = &FeishuWebhook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(feishuwebhook.Table, sqlgraph.NewFieldSpec(feishuwebhook.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(feishuwebhook.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.EncryptedURL(); ok {
		_spec.SetField(feishuwebhook.FieldEncryptedURL, field.TypeString, value)
		_node.EncryptedURL = value
	}
	if value, ok := _c.mutation.URLHash(); ok {
		_spec.SetField(feishuwebhook.FieldURLHash, field.TypeString, value)
		_node.URLHash = value
	}
	if value, ok := _c.mutation.Scene(); ok {
		_spec.SetField(feishuwebhook.FieldScene, field.TypeString, value)
		_node.Scene = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(feishuwebhook.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.RateLimitRps(); ok {
		_spec.SetField(feishuwebhook.FieldRateLimitRps, field.TypeFloat64, value)
		_node.RateLimitRps = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(feishuwebhook.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(feishuwebhook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(feishuwebhook.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FeishuWebhook.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FeishuWebhookUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *FeishuWebhookCreate) OnConflict(opts ...sql.ConflictOption) *FeishuWebhookUpsertOne {
	_c.conflict = opts
	return &FeishuWebhookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FeishuWebhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FeishuWebhookCreate) OnConflictColumns(columns ...string) *FeishuWebhookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FeishuWebhookUpsertOne{
		create: _c,
	}
}

type (
	// FeishuWebhookUpsertOne is the builder for "upsert"-ing
	//  one FeishuWebhook node.
	FeishuWebhookUpsertOne struct {
		create *FeishuWebhookCreate
	}

	// FeishuWebhookUpsert is the "OnConflict" setter.
	FeishuWebhookUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *FeishuWebhookUpsert) SetName(v string) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateName() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldName)
	return u
}

// SetEncryptedURL sets the "encrypted_url" field.
func (u *FeishuWebhookUpsert) SetEncryptedURL(v string) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldEncryptedURL, v)
	return u
}

// UpdateEncryptedURL sets the "encrypted_url" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateEncryptedURL() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldEncryptedURL)
	return u
}

// SetURLHash sets the "url_hash" field.
func (u *FeishuWebhookUpsert) SetURLHash(v string) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldURLHash, v)
	return u
}

// UpdateURLHash sets the "url_hash" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateURLHash() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldURLHash)
	return u
}

// SetScene sets the "scene" field.
func (u *FeishuWebhookUpsert) SetScene(v string) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldScene, v)
	return u
}

// UpdateScene sets the "scene" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateScene() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldScene)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *FeishuWebhookUpsert) SetEnabled(v bool) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateEnabled() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldEnabled)
	return u
}

// SetRateLimitRps sets the "rate_limit_rps" field.
func (u *FeishuWebhookUpsert) SetRateLimitRps(v float64) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldRateLimitRps, v)
	return u
}

// UpdateRateLimitRps sets the "rate_limit_rps" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateRateLimitRps() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldRateLimitRps)
	return u
}

// AddRateLimitRps adds v to the "rate_limit_rps" field.
func (u *FeishuWebhookUpsert) AddRateLimitRps(v float64) *FeishuWebhookUpsert {
	u.Add(feishuwebhook.FieldRateLimitRps, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *FeishuWebhookUpsert) SetCreatedBy(v string) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateCreatedBy() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldCreatedBy)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *FeishuWebhookUpsert) SetCreatedAt(v time.Time) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateCreatedAt() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FeishuWebhookUpsert) SetUpdatedAt(v time.Time) *FeishuWebhookUpsert {
	u.Set(feishuwebhook.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FeishuWebhookUpsert) UpdateUpdatedAt() *FeishuWebhookUpsert {
	u.SetExcluded(feishuwebhook.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FeishuWebhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FeishuWebhookUpsertOne) UpdateNewValues() *FeishuWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FeishuWebhook.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FeishuWebhookUpsertOne) Ignore() *FeishuWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FeishuWebhookUpsertOne) DoNothing() *FeishuWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FeishuWebhookCreate.OnConflict
// documentation for more info.
func (u *FeishuWebhookUpsertOne) Update(set func(*FeishuWebhookUpsert)) *FeishuWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FeishuWebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *FeishuWebhookUpsertOne) SetName(v string) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateName() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateName()
	})
}

// SetEncryptedURL sets the "encrypted_url" field.
func (u *FeishuWebhookUpsertOne) SetEncryptedURL(v string) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetEncryptedURL(v)
	})
}

// UpdateEncryptedURL sets the "encrypted_url" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateEncryptedURL() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateEncryptedURL()
	})
}

// SetURLHash sets the "url_hash" field.
func (u *FeishuWebhookUpsertOne) SetURLHash(v string) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetURLHash(v)
	})
}

// UpdateURLHash sets the "url_hash" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateURLHash() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateURLHash()
	})
}

// SetScene sets the "scene" field.
func (u *FeishuWebhookUpsertOne) SetScene(v string) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetScene(v)
	})
}

// UpdateScene sets the "scene" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateScene() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateScene()
	})
}

// SetEnabled sets the "enabled" field.
func (u *FeishuWebhookUpsertOne) SetEnabled(v bool) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateEnabled() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateEnabled()
	})
}

// SetRateLimitRps sets the "rate_limit_rps" field.
func (u *FeishuWebhookUpsertOne) SetRateLimitRps(v float64) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetRateLimitRps(v)
	})
}

// AddRateLimitRps adds v to the "rate_limit_rps" field.
func (u *FeishuWebhookUpsertOne) AddRateLimitRps(v float64) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.AddRateLimitRps(v)
	})
}

// UpdateRateLimitRps sets the "rate_limit_rps" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateRateLimitRps() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateRateLimitRps()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *FeishuWebhookUpsertOne) SetCreatedBy(v string) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateCreatedBy() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *FeishuWebhookUpsertOne) SetCreatedAt(v time.Time) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateCreatedAt() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FeishuWebhookUpsertOne) SetUpdatedAt(v time.Time) *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FeishuWebhookUpsertOne) UpdateUpdatedAt() *FeishuWebhookUpsertOne {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *FeishuWebhookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FeishuWebhookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FeishuWebhookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FeishuWebhookUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FeishuWebhookUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FeishuWebhookCreateBulk is the builder for creating many FeishuWebhook entities in bulk.
type FeishuWebhookCreateBulk struct {
	config
	err      error
	builders []*FeishuWebhookCreate
	conflict []sql.ConflictOption
}

// Save creates the FeishuWebhook entities in the database.
func (_c *FeishuWebhookCreateBulk) Save(ctx context.Context) ([]*FeishuWebhook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FeishuWebhook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeishuWebhookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FeishuWebhookCreateBulk) SaveX(ctx context.Context) []*FeishuWebhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeishuWebhookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeishuWebhookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FeishuWebhook.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FeishuWebhookUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *FeishuWebhookCreateBulk) OnConflict(opts ...sql.ConflictOption) *FeishuWebhookUpsertBulk {
	_c.conflict = opts
	return &FeishuWebhookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FeishuWebhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FeishuWebhookCreateBulk) OnConflictColumns(columns ...string) *FeishuWebhookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FeishuWebhookUpsertBulk{
		create: _c,
	}
}

// FeishuWebhookUpsertBulk is the builder for "upsert"-ing
// a bulk of FeishuWebhook nodes.
type FeishuWebhookUpsertBulk struct {
	create *FeishuWebhookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FeishuWebhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FeishuWebhookUpsertBulk) UpdateNewValues() *FeishuWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FeishuWebhook.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FeishuWebhookUpsertBulk) Ignore() *FeishuWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FeishuWebhookUpsertBulk) DoNothing() *FeishuWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FeishuWebhookCreateBulk.OnConflict
// documentation for more info.
func (u *FeishuWebhookUpsertBulk) Update(set func(*FeishuWebhookUpsert)) *FeishuWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FeishuWebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *FeishuWebhookUpsertBulk) SetName(v string) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateName() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateName()
	})
}

// SetEncryptedURL sets the "encrypted_url" field.
func (u *FeishuWebhookUpsertBulk) SetEncryptedURL(v string) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetEncryptedURL(v)
	})
}

// UpdateEncryptedURL sets the "encrypted_url" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateEncryptedURL() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateEncryptedURL()
	})
}

// SetURLHash sets the "url_hash" field.
func (u *FeishuWebhookUpsertBulk) SetURLHash(v string) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetURLHash(v)
	})
}

// UpdateURLHash sets the "url_hash" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateURLHash() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateURLHash()
	})
}

// SetScene sets the "scene" field.
func (u *FeishuWebhookUpsertBulk) SetScene(v string) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetScene(v)
	})
}

// UpdateScene sets the "scene" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateScene() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateScene()
	})
}

// SetEnabled sets the "enabled" field.
func (u *FeishuWebhookUpsertBulk) SetEnabled(v bool) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateEnabled() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateEnabled()
	})
}

// SetRateLimitRps sets the "rate_limit_rps" field.
func (u *FeishuWebhookUpsertBulk) SetRateLimitRps(v float64) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetRateLimitRps(v)
	})
}

// AddRateLimitRps adds v to the "rate_limit_rps" field.
func (u *FeishuWebhookUpsertBulk) AddRateLimitRps(v float64) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.AddRateLimitRps(v)
	})
}

// UpdateRateLimitRps sets the "rate_limit_rps" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateRateLimitRps() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateRateLimitRps()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *FeishuWebhookUpsertBulk) SetCreatedBy(v string) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateCreatedBy() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *FeishuWebhookUpsertBulk) SetCreatedAt(v time.Time) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateCreatedAt() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FeishuWebhookUpsertBulk) SetUpdatedAt(v time.Time) *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FeishuWebhookUpsertBulk) UpdateUpdatedAt() *FeishuWebhookUpsertBulk {
	return u.Update(func(s *FeishuWebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *FeishuWebhookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FeishuWebhookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FeishuWebhookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FeishuWebhookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
