// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/feishudeadletter"
)

// FeishuDeadLetterCreate is the builder for creating a FeishuDeadLetter entity.
type FeishuDeadLetterCreate struct {
	config
	mutation *FeishuDeadLetterMutation
	hooks    []Hook
}

// SetWebhookID sets the "webhook_id" field.
func (_c *FeishuDeadLetterCreate) SetWebhookID(v int64) *FeishuDeadLetterCreate {
	_c.mutation.SetWebhookID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *FeishuDeadLetterCreate) SetPayload(v string) *FeishuDeadLetterCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *FeishuDeadLetterCreate) SetErrorMessage(v string) *FeishuDeadLetterCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *FeishuDeadLetterCreate) SetNillableErrorMessage(v *string) *FeishuDeadLetterCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *FeishuDeadLetterCreate) SetAttemptCount(v int64) *FeishuDeadLetterCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *FeishuDeadLetterCreate) SetNillableAttemptCount(v *int64) *FeishuDeadLetterCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_c *FeishuDeadLetterCreate) SetLastAttemptAt(v time.Time) *FeishuDeadLetterCreate {
	_c.mutation.SetLastAttemptAt(v)
	return _c
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_c *FeishuDeadLetterCreate) SetNillableLastAttemptAt(v *time.Time) *FeishuDeadLetterCreate {
	if v != nil {
		_c.SetLastAttemptAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FeishuDeadLetterCreate) SetCreatedAt(v time.Time) *FeishuDeadLetterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FeishuDeadLetterCreate) SetNillableCreatedAt(v *time.Time) *FeishuDeadLetterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the FeishuDeadLetterMutation object of the builder.
func (_c *FeishuDeadLetterCreate) Mutation() *FeishuDeadLetterMutation {
	return _c.mutation
}

// Save creates the FeishuDeadLetter in the database.
func (_c *FeishuDeadLetterCreate) Save(ctx context.Context) (*FeishuDeadLetter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FeishuDeadLetterCreate) SaveX(ctx context.Context) *FeishuDeadLetter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeishuDeadLetterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeishuDeadLetterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FeishuDeadLetterCreate) defaults() {
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := feishudeadletter.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := feishudeadletter.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.LastAttemptAt(); !ok {
		v := feishudeadletter.DefaultLastAttemptAt()
		_c.mutation.SetLastAttemptAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := feishudeadletter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FeishuDeadLetterCreate) check() error {
	if _, ok := _c.mutation.WebhookID(); !ok {
		return &ValidationError{Name: "webhook_id", err: errors.New(`ent: missing required field "FeishuDeadLetter.webhook_id"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "FeishuDeadLetter.payload"`)}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "FeishuDeadLetter.error_message"`)}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "FeishuDeadLetter.attempt_count"`)}
	}
	return nil
}

func (_c *FeishuDeadLetterCreate) sqlSave(ctx context.Context) (*FeishuDeadLetter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FeishuDeadLetterCreate) createSpec() (*FeishuDeadLetter, *sqlgraph.CreateSpec) {
	var (
		_node = &FeishuDeadLetter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(feishudeadletter.Table, sqlgraph.NewFieldSpec(feishudeadletter.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.WebhookID(); ok {
		_spec.SetField(feishudeadletter.FieldWebhookID, field.TypeInt64, value)
		_node.WebhookID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(feishudeadletter.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(feishudeadletter.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(feishudeadletter.FieldAttemptCount, field.TypeInt64, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.LastAttemptAt(); ok {
		_spec.SetField(feishudeadletter.FieldLastAttemptAt, field.TypeTime, value)
		_node.LastAttemptAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(feishudeadletter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// FeishuDeadLetterCreateBulk is the builder for creating many FeishuDeadLetter entities in bulk.
type FeishuDeadLetterCreateBulk struct {
	config
	err      error
	builders []*FeishuDeadLetterCreate
}

// Save creates the FeishuDeadLetter entities in the database.
func (_c *FeishuDeadLetterCreateBulk) Save(ctx context.Context) ([]*FeishuDeadLetter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FeishuDeadLetter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeishuDeadLetterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FeishuDeadLetterCreateBulk) SaveX(ctx context.Context) []*FeishuDeadLetter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeishuDeadLetterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeishuDeadLetterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
