// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/gitlink"
)

// GitLinkCreate is the builder for creating a GitLink entity.
type GitLinkCreate struct {
	config
	mutation *GitLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEntityType sets the "entity_type" field.
func (_c *GitLinkCreate) SetEntityType(v string) *GitLinkCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableEntityType(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetEntityType(*v)
	}
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *GitLinkCreate) SetEntityID(v int64) *GitLinkCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableEntityID(v *int64) *GitLinkCreate {
	if v != nil {
		_c.SetEntityID(*v)
	}
	return _c
}

// SetLinkType sets the "link_type" field.
func (_c *GitLinkCreate) SetLinkType(v string) *GitLinkCreate {
	_c.mutation.SetLinkType(v)
	return _c
}

// SetNillableLinkType sets the "link_type" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableLinkType(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetLinkType(*v)
	}
	return _c
}

// SetCommitHash sets the "commit_hash" field.
func (_c *GitLinkCreate) SetCommitHash(v string) *GitLinkCreate {
	_c.mutation.SetCommitHash(v)
	return _c
}

// SetNillableCommitHash sets the "commit_hash" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableCommitHash(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetCommitHash(*v)
	}
	return _c
}

// SetCommitMsg sets the "commit_msg" field.
func (_c *GitLinkCreate) SetCommitMsg(v string) *GitLinkCreate {
	_c.mutation.SetCommitMsg(v)
	return _c
}

// SetNillableCommitMsg sets the "commit_msg" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableCommitMsg(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetCommitMsg(*v)
	}
	return _c
}

// SetAuthorName sets the "author_name" field.
func (_c *GitLinkCreate) SetAuthorName(v string) *GitLinkCreate {
	_c.mutation.SetAuthorName(v)
	return _c
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableAuthorName(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetAuthorName(*v)
	}
	return _c
}

// SetAuthorEmail sets the "author_email" field.
func (_c *GitLinkCreate) SetAuthorEmail(v string) *GitLinkCreate {
	_c.mutation.SetAuthorEmail(v)
	return _c
}

// SetNillableAuthorEmail sets the "author_email" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableAuthorEmail(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetAuthorEmail(*v)
	}
	return _c
}

// SetPrNumber sets the "pr_number" field.
func (_c *GitLinkCreate) SetPrNumber(v int) *GitLinkCreate {
	_c.mutation.SetPrNumber(v)
	return _c
}

// SetNillablePrNumber sets the "pr_number" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillablePrNumber(v *int) *GitLinkCreate {
	if v != nil {
		_c.SetPrNumber(*v)
	}
	return _c
}

// SetPrTitle sets the "pr_title" field.
func (_c *GitLinkCreate) SetPrTitle(v string) *GitLinkCreate {
	_c.mutation.SetPrTitle(v)
	return _c
}

// SetNillablePrTitle sets the "pr_title" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillablePrTitle(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetPrTitle(*v)
	}
	return _c
}

// SetPrURL sets the "pr_url" field.
func (_c *GitLinkCreate) SetPrURL(v string) *GitLinkCreate {
	_c.mutation.SetPrURL(v)
	return _c
}

// SetNillablePrURL sets the "pr_url" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillablePrURL(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetPrURL(*v)
	}
	return _c
}

// SetRepoURL sets the "repo_url" field.
func (_c *GitLinkCreate) SetRepoURL(v string) *GitLinkCreate {
	_c.mutation.SetRepoURL(v)
	return _c
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableRepoURL(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetRepoURL(*v)
	}
	return _c
}

// SetBranch sets the "branch" field.
func (_c *GitLinkCreate) SetBranch(v string) *GitLinkCreate {
	_c.mutation.SetBranch(v)
	return _c
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableBranch(v *string) *GitLinkCreate {
	if v != nil {
		_c.SetBranch(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GitLinkCreate) SetCreatedBy(v int64) *GitLinkCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableCreatedBy(v *int64) *GitLinkCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GitLinkCreate) SetCreatedAt(v time.Time) *GitLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GitLinkCreate) SetNillableCreatedAt(v *time.Time) *GitLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the GitLinkMutation object of the builder.
func (_c *GitLinkCreate) Mutation() *GitLinkMutation {
	return _c.mutation
}

// Save creates the GitLink in the database.
func (_c *GitLinkCreate) Save(ctx context.Context) (*GitLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GitLinkCreate) SaveX(ctx context.Context) *GitLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GitLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GitLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GitLinkCreate) defaults() {
	if _, ok := _c.mutation.EntityType(); !ok {
		v := gitlink.DefaultEntityType
		_c.mutation.SetEntityType(v)
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		v := gitlink.DefaultEntityID
		_c.mutation.SetEntityID(v)
	}
	if _, ok := _c.mutation.LinkType(); !ok {
		v := gitlink.DefaultLinkType
		_c.mutation.SetLinkType(v)
	}
	if _, ok := _c.mutation.CommitHash(); !ok {
		v := gitlink.DefaultCommitHash
		_c.mutation.SetCommitHash(v)
	}
	if _, ok := _c.mutation.CommitMsg(); !ok {
		v := gitlink.DefaultCommitMsg
		_c.mutation.SetCommitMsg(v)
	}
	if _, ok := _c.mutation.AuthorName(); !ok {
		v := gitlink.DefaultAuthorName
		_c.mutation.SetAuthorName(v)
	}
	if _, ok := _c.mutation.AuthorEmail(); !ok {
		v := gitlink.DefaultAuthorEmail
		_c.mutation.SetAuthorEmail(v)
	}
	if _, ok := _c.mutation.PrNumber(); !ok {
		v := gitlink.DefaultPrNumber
		_c.mutation.SetPrNumber(v)
	}
	if _, ok := _c.mutation.PrTitle(); !ok {
		v := gitlink.DefaultPrTitle
		_c.mutation.SetPrTitle(v)
	}
	if _, ok := _c.mutation.PrURL(); !ok {
		v := gitlink.DefaultPrURL
		_c.mutation.SetPrURL(v)
	}
	if _, ok := _c.mutation.RepoURL(); !ok {
		v := gitlink.DefaultRepoURL
		_c.mutation.SetRepoURL(v)
	}
	if _, ok := _c.mutation.Branch(); !ok {
		v := gitlink.DefaultBranch
		_c.mutation.SetBranch(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := gitlink.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gitlink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GitLinkCreate) check() error {
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "GitLink.entity_type"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "GitLink.entity_id"`)}
	}
	if _, ok := _c.mutation.LinkType(); !ok {
		return &ValidationError{Name: "link_type", err: errors.New(`ent: missing required field "GitLink.link_type"`)}
	}
	if _, ok := _c.mutation.CommitHash(); !ok {
		return &ValidationError{Name: "commit_hash", err: errors.New(`ent: missing required field "GitLink.commit_hash"`)}
	}
	if _, ok := _c.mutation.CommitMsg(); !ok {
		return &ValidationError{Name: "commit_msg", err: errors.New(`ent: missing required field "GitLink.commit_msg"`)}
	}
	if _, ok := _c.mutation.AuthorName(); !ok {
		return &ValidationError{Name: "author_name", err: errors.New(`ent: missing required field "GitLink.author_name"`)}
	}
	if _, ok := _c.mutation.AuthorEmail(); !ok {
		return &ValidationError{Name: "author_email", err: errors.New(`ent: missing required field "GitLink.author_email"`)}
	}
	if _, ok := _c.mutation.PrNumber(); !ok {
		return &ValidationError{Name: "pr_number", err: errors.New(`ent: missing required field "GitLink.pr_number"`)}
	}
	if _, ok := _c.mutation.PrTitle(); !ok {
		return &ValidationError{Name: "pr_title", err: errors.New(`ent: missing required field "GitLink.pr_title"`)}
	}
	if _, ok := _c.mutation.PrURL(); !ok {
		return &ValidationError{Name: "pr_url", err: errors.New(`ent: missing required field "GitLink.pr_url"`)}
	}
	if _, ok := _c.mutation.RepoURL(); !ok {
		return &ValidationError{Name: "repo_url", err: errors.New(`ent: missing required field "GitLink.repo_url"`)}
	}
	if _, ok := _c.mutation.Branch(); !ok {
		return &ValidationError{Name: "branch", err: errors.New(`ent: missing required field "GitLink.branch"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "GitLink.created_by"`)}
	}
	return nil
}

func (_c *GitLinkCreate) sqlSave(ctx context.Context) (*GitLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GitLinkCreate) createSpec() (*GitLink, *sqlgraph.CreateSpec) {
	var (
		_node = &GitLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gitlink.Table, sqlgraph.NewFieldSpec(gitlink.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(gitlink.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(gitlink.FieldEntityID, field.TypeInt64, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.LinkType(); ok {
		_spec.SetField(gitlink.FieldLinkType, field.TypeString, value)
		_node.LinkType = value
	}
	if value, ok := _c.mutation.CommitHash(); ok {
		_spec.SetField(gitlink.FieldCommitHash, field.TypeString, value)
		_node.CommitHash = value
	}
	if value, ok := _c.mutation.CommitMsg(); ok {
		_spec.SetField(gitlink.FieldCommitMsg, field.TypeString, value)
		_node.CommitMsg = value
	}
	if value, ok := _c.mutation.AuthorName(); ok {
		_spec.SetField(gitlink.FieldAuthorName, field.TypeString, value)
		_node.AuthorName = value
	}
	if value, ok := _c.mutation.AuthorEmail(); ok {
		_spec.SetField(gitlink.FieldAuthorEmail, field.TypeString, value)
		_node.AuthorEmail = value
	}
	if value, ok := _c.mutation.PrNumber(); ok {
		_spec.SetField(gitlink.FieldPrNumber, field.TypeInt, value)
		_node.PrNumber = value
	}
	if value, ok := _c.mutation.PrTitle(); ok {
		_spec.SetField(gitlink.FieldPrTitle, field.TypeString, value)
		_node.PrTitle = value
	}
	if value, ok := _c.mutation.PrURL(); ok {
		_spec.SetField(gitlink.FieldPrURL, field.TypeString, value)
		_node.PrURL = value
	}
	if value, ok := _c.mutation.RepoURL(); ok {
		_spec.SetField(gitlink.FieldRepoURL, field.TypeString, value)
		_node.RepoURL = value
	}
	if value, ok := _c.mutation.Branch(); ok {
		_spec.SetField(gitlink.FieldBranch, field.TypeString, value)
		_node.Branch = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(gitlink.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gitlink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GitLink.Create().
//		SetEntityType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GitLinkUpsert) {
//			SetEntityType(v+v).
//		}).
//		Exec(ctx)
func (_c *GitLinkCreate) OnConflict(opts ...sql.ConflictOption) *GitLinkUpsertOne {
	_c.conflict = opts
	return &GitLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GitLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GitLinkCreate) OnConflictColumns(columns ...string) *GitLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GitLinkUpsertOne{
		create: _c,
	}
}

type (
	// GitLinkUpsertOne is the builder for "upsert"-ing
	//  one GitLink node.
	GitLinkUpsertOne struct {
		create *GitLinkCreate
	}

	// GitLinkUpsert is the "OnConflict" setter.
	GitLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetEntityType sets the "entity_type" field.
func (u *GitLinkUpsert) SetEntityType(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldEntityType, v)
	return u
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateEntityType() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldEntityType)
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *GitLinkUpsert) SetEntityID(v int64) *GitLinkUpsert {
	u.Set(gitlink.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateEntityID() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldEntityID)
	return u
}

// AddEntityID adds v to the "entity_id" field.
func (u *GitLinkUpsert) AddEntityID(v int64) *GitLinkUpsert {
	u.Add(gitlink.FieldEntityID, v)
	return u
}

// SetLinkType sets the "link_type" field.
func (u *GitLinkUpsert) SetLinkType(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldLinkType, v)
	return u
}

// UpdateLinkType sets the "link_type" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateLinkType() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldLinkType)
	return u
}

// SetCommitHash sets the "commit_hash" field.
func (u *GitLinkUpsert) SetCommitHash(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldCommitHash, v)
	return u
}

// UpdateCommitHash sets the "commit_hash" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateCommitHash() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldCommitHash)
	return u
}

// SetCommitMsg sets the "commit_msg" field.
func (u *GitLinkUpsert) SetCommitMsg(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldCommitMsg, v)
	return u
}

// UpdateCommitMsg sets the "commit_msg" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateCommitMsg() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldCommitMsg)
	return u
}

// SetAuthorName sets the "author_name" field.
func (u *GitLinkUpsert) SetAuthorName(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldAuthorName, v)
	return u
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateAuthorName() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldAuthorName)
	return u
}

// SetAuthorEmail sets the "author_email" field.
func (u *GitLinkUpsert) SetAuthorEmail(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldAuthorEmail, v)
	return u
}

// UpdateAuthorEmail sets the "author_email" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateAuthorEmail() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldAuthorEmail)
	return u
}

// SetPrNumber sets the "pr_number" field.
func (u *GitLinkUpsert) SetPrNumber(v int) *GitLinkUpsert {
	u.Set(gitlink.FieldPrNumber, v)
	return u
}

// UpdatePrNumber sets the "pr_number" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdatePrNumber() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldPrNumber)
	return u
}

// AddPrNumber adds v to the "pr_number" field.
func (u *GitLinkUpsert) AddPrNumber(v int) *GitLinkUpsert {
	u.Add(gitlink.FieldPrNumber, v)
	return u
}

// SetPrTitle sets the "pr_title" field.
func (u *GitLinkUpsert) SetPrTitle(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldPrTitle, v)
	return u
}

// UpdatePrTitle sets the "pr_title" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdatePrTitle() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldPrTitle)
	return u
}

// SetPrURL sets the "pr_url" field.
func (u *GitLinkUpsert) SetPrURL(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldPrURL, v)
	return u
}

// UpdatePrURL sets the "pr_url" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdatePrURL() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldPrURL)
	return u
}

// SetRepoURL sets the "repo_url" field.
func (u *GitLinkUpsert) SetRepoURL(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldRepoURL, v)
	return u
}

// UpdateRepoURL sets the "repo_url" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateRepoURL() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldRepoURL)
	return u
}

// SetBranch sets the "branch" field.
func (u *GitLinkUpsert) SetBranch(v string) *GitLinkUpsert {
	u.Set(gitlink.FieldBranch, v)
	return u
}

// UpdateBranch sets the "branch" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateBranch() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldBranch)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *GitLinkUpsert) SetCreatedBy(v int64) *GitLinkUpsert {
	u.Set(gitlink.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateCreatedBy() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GitLinkUpsert) AddCreatedBy(v int64) *GitLinkUpsert {
	u.Add(gitlink.FieldCreatedBy, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GitLinkUpsert) SetCreatedAt(v time.Time) *GitLinkUpsert {
	u.Set(gitlink.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GitLinkUpsert) UpdateCreatedAt() *GitLinkUpsert {
	u.SetExcluded(gitlink.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GitLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GitLinkUpsertOne) UpdateNewValues() *GitLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GitLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GitLinkUpsertOne) Ignore() *GitLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GitLinkUpsertOne) DoNothing() *GitLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GitLinkCreate.OnConflict
// documentation for more info.
func (u *GitLinkUpsertOne) Update(set func(*GitLinkUpsert)) *GitLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GitLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntityType sets the "entity_type" field.
func (u *GitLinkUpsertOne) SetEntityType(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateEntityType() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateEntityType()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *GitLinkUpsertOne) SetEntityID(v int64) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetEntityID(v)
	})
}

// AddEntityID adds v to the "entity_id" field.
func (u *GitLinkUpsertOne) AddEntityID(v int64) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.AddEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateEntityID() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateEntityID()
	})
}

// SetLinkType sets the "link_type" field.
func (u *GitLinkUpsertOne) SetLinkType(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetLinkType(v)
	})
}

// UpdateLinkType sets the "link_type" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateLinkType() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateLinkType()
	})
}

// SetCommitHash sets the "commit_hash" field.
func (u *GitLinkUpsertOne) SetCommitHash(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCommitHash(v)
	})
}

// UpdateCommitHash sets the "commit_hash" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateCommitHash() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCommitHash()
	})
}

// SetCommitMsg sets the "commit_msg" field.
func (u *GitLinkUpsertOne) SetCommitMsg(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCommitMsg(v)
	})
}

// UpdateCommitMsg sets the "commit_msg" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateCommitMsg() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCommitMsg()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *GitLinkUpsertOne) SetAuthorName(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateAuthorName() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateAuthorName()
	})
}

// SetAuthorEmail sets the "author_email" field.
func (u *GitLinkUpsertOne) SetAuthorEmail(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetAuthorEmail(v)
	})
}

// UpdateAuthorEmail sets the "author_email" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateAuthorEmail() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateAuthorEmail()
	})
}

// SetPrNumber sets the "pr_number" field.
func (u *GitLinkUpsertOne) SetPrNumber(v int) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetPrNumber(v)
	})
}

// AddPrNumber adds v to the "pr_number" field.
func (u *GitLinkUpsertOne) AddPrNumber(v int) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.AddPrNumber(v)
	})
}

// UpdatePrNumber sets the "pr_number" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdatePrNumber() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdatePrNumber()
	})
}

// SetPrTitle sets the "pr_title" field.
func (u *GitLinkUpsertOne) SetPrTitle(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetPrTitle(v)
	})
}

// UpdatePrTitle sets the "pr_title" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdatePrTitle() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdatePrTitle()
	})
}

// SetPrURL sets the "pr_url" field.
func (u *GitLinkUpsertOne) SetPrURL(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetPrURL(v)
	})
}

// UpdatePrURL sets the "pr_url" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdatePrURL() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdatePrURL()
	})
}

// SetRepoURL sets the "repo_url" field.
func (u *GitLinkUpsertOne) SetRepoURL(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetRepoURL(v)
	})
}

// UpdateRepoURL sets the "repo_url" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateRepoURL() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateRepoURL()
	})
}

// SetBranch sets the "branch" field.
func (u *GitLinkUpsertOne) SetBranch(v string) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetBranch(v)
	})
}

// UpdateBranch sets the "branch" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateBranch() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateBranch()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *GitLinkUpsertOne) SetCreatedBy(v int64) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GitLinkUpsertOne) AddCreatedBy(v int64) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateCreatedBy() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GitLinkUpsertOne) SetCreatedAt(v time.Time) *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GitLinkUpsertOne) UpdateCreatedAt() *GitLinkUpsertOne {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *GitLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GitLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GitLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GitLinkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GitLinkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GitLinkCreateBulk is the builder for creating many GitLink entities in bulk.
type GitLinkCreateBulk struct {
	config
	err      error
	builders []*GitLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the GitLink entities in the database.
func (_c *GitLinkCreateBulk) Save(ctx context.Context) ([]*GitLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GitLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GitLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GitLinkCreateBulk) SaveX(ctx context.Context) []*GitLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GitLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GitLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GitLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GitLinkUpsert) {
//			SetEntityType(v+v).
//		}).
//		Exec(ctx)
func (_c *GitLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *GitLinkUpsertBulk {
	_c.conflict = opts
	return &GitLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GitLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GitLinkCreateBulk) OnConflictColumns(columns ...string) *GitLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GitLinkUpsertBulk{
		create: _c,
	}
}

// GitLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of GitLink nodes.
type GitLinkUpsertBulk struct {
	create *GitLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GitLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GitLinkUpsertBulk) UpdateNewValues() *GitLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GitLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GitLinkUpsertBulk) Ignore() *GitLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GitLinkUpsertBulk) DoNothing() *GitLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GitLinkCreateBulk.OnConflict
// documentation for more info.
func (u *GitLinkUpsertBulk) Update(set func(*GitLinkUpsert)) *GitLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GitLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntityType sets the "entity_type" field.
func (u *GitLinkUpsertBulk) SetEntityType(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetEntityType(v)
	})
}

// UpdateEntityType sets the "entity_type" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateEntityType() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateEntityType()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *GitLinkUpsertBulk) SetEntityID(v int64) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetEntityID(v)
	})
}

// AddEntityID adds v to the "entity_id" field.
func (u *GitLinkUpsertBulk) AddEntityID(v int64) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.AddEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateEntityID() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateEntityID()
	})
}

// SetLinkType sets the "link_type" field.
func (u *GitLinkUpsertBulk) SetLinkType(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetLinkType(v)
	})
}

// UpdateLinkType sets the "link_type" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateLinkType() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateLinkType()
	})
}

// SetCommitHash sets the "commit_hash" field.
func (u *GitLinkUpsertBulk) SetCommitHash(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCommitHash(v)
	})
}

// UpdateCommitHash sets the "commit_hash" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateCommitHash() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCommitHash()
	})
}

// SetCommitMsg sets the "commit_msg" field.
func (u *GitLinkUpsertBulk) SetCommitMsg(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCommitMsg(v)
	})
}

// UpdateCommitMsg sets the "commit_msg" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateCommitMsg() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCommitMsg()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *GitLinkUpsertBulk) SetAuthorName(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateAuthorName() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateAuthorName()
	})
}

// SetAuthorEmail sets the "author_email" field.
func (u *GitLinkUpsertBulk) SetAuthorEmail(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetAuthorEmail(v)
	})
}

// UpdateAuthorEmail sets the "author_email" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateAuthorEmail() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateAuthorEmail()
	})
}

// SetPrNumber sets the "pr_number" field.
func (u *GitLinkUpsertBulk) SetPrNumber(v int) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetPrNumber(v)
	})
}

// AddPrNumber adds v to the "pr_number" field.
func (u *GitLinkUpsertBulk) AddPrNumber(v int) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.AddPrNumber(v)
	})
}

// UpdatePrNumber sets the "pr_number" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdatePrNumber() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdatePrNumber()
	})
}

// SetPrTitle sets the "pr_title" field.
func (u *GitLinkUpsertBulk) SetPrTitle(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetPrTitle(v)
	})
}

// UpdatePrTitle sets the "pr_title" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdatePrTitle() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdatePrTitle()
	})
}

// SetPrURL sets the "pr_url" field.
func (u *GitLinkUpsertBulk) SetPrURL(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetPrURL(v)
	})
}

// UpdatePrURL sets the "pr_url" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdatePrURL() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdatePrURL()
	})
}

// SetRepoURL sets the "repo_url" field.
func (u *GitLinkUpsertBulk) SetRepoURL(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetRepoURL(v)
	})
}

// UpdateRepoURL sets the "repo_url" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateRepoURL() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateRepoURL()
	})
}

// SetBranch sets the "branch" field.
func (u *GitLinkUpsertBulk) SetBranch(v string) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetBranch(v)
	})
}

// UpdateBranch sets the "branch" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateBranch() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateBranch()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *GitLinkUpsertBulk) SetCreatedBy(v int64) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GitLinkUpsertBulk) AddCreatedBy(v int64) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateCreatedBy() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GitLinkUpsertBulk) SetCreatedAt(v time.Time) *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GitLinkUpsertBulk) UpdateCreatedAt() *GitLinkUpsertBulk {
	return u.Update(func(s *GitLinkUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *GitLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GitLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GitLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GitLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
