// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/oidcprovider"
)

// OIDCProviderCreate is the builder for creating a OIDCProvider entity.
type OIDCProviderCreate struct {
	config
	mutation *OIDCProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *OIDCProviderCreate) SetName(v string) *OIDCProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *OIDCProviderCreate) SetIssuer(v string) *OIDCProviderCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OIDCProviderCreate) SetClientID(v string) *OIDCProviderCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *OIDCProviderCreate) SetClientSecret(v string) *OIDCProviderCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_c *OIDCProviderCreate) SetNillableClientSecret(v *string) *OIDCProviderCreate {
	if v != nil {
		_c.SetClientSecret(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OIDCProviderCreate) SetScopes(v string) *OIDCProviderCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_c *OIDCProviderCreate) SetNillableScopes(v *string) *OIDCProviderCreate {
	if v != nil {
		_c.SetScopes(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *OIDCProviderCreate) SetEnabled(v bool) *OIDCProviderCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *OIDCProviderCreate) SetNillableEnabled(v *bool) *OIDCProviderCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OIDCProviderCreate) SetCreatedAt(v time.Time) *OIDCProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OIDCProviderCreate) SetNillableCreatedAt(v *time.Time) *OIDCProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OIDCProviderCreate) SetUpdatedAt(v time.Time) *OIDCProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OIDCProviderCreate) SetNillableUpdatedAt(v *time.Time) *OIDCProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OIDCProviderMutation object of the builder.
func (_c *OIDCProviderCreate) Mutation() *OIDCProviderMutation {
	return _c.mutation
}

// Save creates the OIDCProvider in the database.
func (_c *OIDCProviderCreate) Save(ctx context.Context) (*OIDCProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCProviderCreate) SaveX(ctx context.Context) *OIDCProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCProviderCreate) defaults() {
	if _, ok := _c.mutation.ClientSecret(); !ok {
		v := oidcprovider.DefaultClientSecret
		_c.mutation.SetClientSecret(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oidcprovider.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := oidcprovider.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oidcprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oidcprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCProviderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OIDCProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oidcprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OIDCProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "OIDCProvider.issuer"`)}
	}
	if v, ok := _c.mutation.Issuer(); ok {
		if err := oidcprovider.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "OIDCProvider.issuer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OIDCProvider.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oidcprovider.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OIDCProvider.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "OIDCProvider.client_secret"`)}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OIDCProvider.scopes"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "OIDCProvider.enabled"`)}
	}
	return nil
}

func (_c *OIDCProviderCreate) sqlSave(ctx context.Context) (*OIDCProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCProviderCreate) createSpec() (*OIDCProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcprovider.Table, sqlgraph.NewFieldSpec(oidcprovider.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oidcprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(oidcprovider.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oidcprovider.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(oidcprovider.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oidcprovider.FieldScopes, field.TypeString, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(oidcprovider.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oidcprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OIDCProvider.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OIDCProviderUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *OIDCProviderCreate) OnConflict(opts ...sql.ConflictOption) *OIDCProviderUpsertOne {
	_c.conflict = opts
	return &OIDCProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OIDCProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OIDCProviderCreate) OnConflictColumns(columns ...string) *OIDCProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OIDCProviderUpsertOne{
		create: _c,
	}
}

type (
	// OIDCProviderUpsertOne is the builder for "upsert"-ing
	//  one OIDCProvider node.
	OIDCProviderUpsertOne struct {
		create *OIDCProviderCreate
	}

	// OIDCProviderUpsert is the "OnConflict" setter.
	OIDCProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *OIDCProviderUpsert) SetName(v string) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateName() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldName)
	return u
}

// SetIssuer sets the "issuer" field.
func (u *OIDCProviderUpsert) SetIssuer(v string) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateIssuer() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldIssuer)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OIDCProviderUpsert) SetClientID(v string) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateClientID() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldClientID)
	return u
}

// SetClientSecret sets the "client_secret" field.
func (u *OIDCProviderUpsert) SetClientSecret(v string) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldClientSecret, v)
	return u
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateClientSecret() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldClientSecret)
	return u
}

// SetScopes sets the "scopes" field.
func (u *OIDCProviderUpsert) SetScopes(v string) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateScopes() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldScopes)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *OIDCProviderUpsert) SetEnabled(v bool) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateEnabled() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldEnabled)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *OIDCProviderUpsert) SetCreatedAt(v time.Time) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateCreatedAt() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OIDCProviderUpsert) SetUpdatedAt(v time.Time) *OIDCProviderUpsert {
	u.Set(oidcprovider.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OIDCProviderUpsert) UpdateUpdatedAt() *OIDCProviderUpsert {
	u.SetExcluded(oidcprovider.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OIDCProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OIDCProviderUpsertOne) UpdateNewValues() *OIDCProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OIDCProvider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OIDCProviderUpsertOne) Ignore() *OIDCProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OIDCProviderUpsertOne) DoNothing() *OIDCProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OIDCProviderCreate.OnConflict
// documentation for more info.
func (u *OIDCProviderUpsertOne) Update(set func(*OIDCProviderUpsert)) *OIDCProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OIDCProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OIDCProviderUpsertOne) SetName(v string) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateName() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateName()
	})
}

// SetIssuer sets the "issuer" field.
func (u *OIDCProviderUpsertOne) SetIssuer(v string) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateIssuer() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateIssuer()
	})
}

// SetClientID sets the "client_id" field.
func (u *OIDCProviderUpsertOne) SetClientID(v string) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateClientID() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateClientID()
	})
}

// SetClientSecret sets the "client_secret" field.
func (u *OIDCProviderUpsertOne) SetClientSecret(v string) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetClientSecret(v)
	})
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateClientSecret() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateClientSecret()
	})
}

// SetScopes sets the "scopes" field.
func (u *OIDCProviderUpsertOne) SetScopes(v string) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateScopes() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateScopes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OIDCProviderUpsertOne) SetEnabled(v bool) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateEnabled() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OIDCProviderUpsertOne) SetCreatedAt(v time.Time) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateCreatedAt() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OIDCProviderUpsertOne) SetUpdatedAt(v time.Time) *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OIDCProviderUpsertOne) UpdateUpdatedAt() *OIDCProviderUpsertOne {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OIDCProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OIDCProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OIDCProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OIDCProviderUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OIDCProviderUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OIDCProviderCreateBulk is the builder for creating many OIDCProvider entities in bulk.
type OIDCProviderCreateBulk struct {
	config
	err      error
	builders []*OIDCProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the OIDCProvider entities in the database.
func (_c *OIDCProviderCreateBulk) Save(ctx context.Context) ([]*OIDCProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCProviderCreateBulk) SaveX(ctx context.Context) []*OIDCProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OIDCProvider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OIDCProviderUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *OIDCProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OIDCProviderUpsertBulk {
	_c.conflict = opts
	return &OIDCProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OIDCProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OIDCProviderCreateBulk) OnConflictColumns(columns ...string) *OIDCProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OIDCProviderUpsertBulk{
		create: _c,
	}
}

// OIDCProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of OIDCProvider nodes.
type OIDCProviderUpsertBulk struct {
	create *OIDCProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OIDCProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OIDCProviderUpsertBulk) UpdateNewValues() *OIDCProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OIDCProvider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OIDCProviderUpsertBulk) Ignore() *OIDCProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OIDCProviderUpsertBulk) DoNothing() *OIDCProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OIDCProviderCreateBulk.OnConflict
// documentation for more info.
func (u *OIDCProviderUpsertBulk) Update(set func(*OIDCProviderUpsert)) *OIDCProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OIDCProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OIDCProviderUpsertBulk) SetName(v string) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateName() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateName()
	})
}

// SetIssuer sets the "issuer" field.
func (u *OIDCProviderUpsertBulk) SetIssuer(v string) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateIssuer() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateIssuer()
	})
}

// SetClientID sets the "client_id" field.
func (u *OIDCProviderUpsertBulk) SetClientID(v string) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateClientID() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateClientID()
	})
}

// SetClientSecret sets the "client_secret" field.
func (u *OIDCProviderUpsertBulk) SetClientSecret(v string) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetClientSecret(v)
	})
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateClientSecret() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateClientSecret()
	})
}

// SetScopes sets the "scopes" field.
func (u *OIDCProviderUpsertBulk) SetScopes(v string) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateScopes() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateScopes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OIDCProviderUpsertBulk) SetEnabled(v bool) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateEnabled() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OIDCProviderUpsertBulk) SetCreatedAt(v time.Time) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateCreatedAt() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OIDCProviderUpsertBulk) SetUpdatedAt(v time.Time) *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OIDCProviderUpsertBulk) UpdateUpdatedAt() *OIDCProviderUpsertBulk {
	return u.Update(func(s *OIDCProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OIDCProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OIDCProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OIDCProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OIDCProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
