// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/permissionrequest"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
)

// PermissionRequestUpdate is the builder for updating PermissionRequest entities.
type PermissionRequestUpdate struct {
	config
	hooks    []Hook
	mutation *PermissionRequestMutation
}

// Where appends a list predicates to the PermissionRequestUpdate builder.
func (_u *PermissionRequestUpdate) Where(ps ...predicate.PermissionRequest) *PermissionRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetApplicantID sets the "applicant_id" field.
func (_u *PermissionRequestUpdate) SetApplicantID(v int64) *PermissionRequestUpdate {
	_u.mutation.ResetApplicantID()
	_u.mutation.SetApplicantID(v)
	return _u
}

// SetNillableApplicantID sets the "applicant_id" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableApplicantID(v *int64) *PermissionRequestUpdate {
	if v != nil {
		_u.SetApplicantID(*v)
	}
	return _u
}

// AddApplicantID adds value to the "applicant_id" field.
func (_u *PermissionRequestUpdate) AddApplicantID(v int64) *PermissionRequestUpdate {
	_u.mutation.AddApplicantID(v)
	return _u
}

// SetDatasourceID sets the "datasource_id" field.
func (_u *PermissionRequestUpdate) SetDatasourceID(v int64) *PermissionRequestUpdate {
	_u.mutation.ResetDatasourceID()
	_u.mutation.SetDatasourceID(v)
	return _u
}

// SetNillableDatasourceID sets the "datasource_id" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableDatasourceID(v *int64) *PermissionRequestUpdate {
	if v != nil {
		_u.SetDatasourceID(*v)
	}
	return _u
}

// AddDatasourceID adds value to the "datasource_id" field.
func (_u *PermissionRequestUpdate) AddDatasourceID(v int64) *PermissionRequestUpdate {
	_u.mutation.AddDatasourceID(v)
	return _u
}

// SetDatabase sets the "database" field.
func (_u *PermissionRequestUpdate) SetDatabase(v string) *PermissionRequestUpdate {
	_u.mutation.SetDatabase(v)
	return _u
}

// SetNillableDatabase sets the "database" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableDatabase(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetDatabase(*v)
	}
	return _u
}

// SetTableName sets the "table_name" field.
func (_u *PermissionRequestUpdate) SetTableName(v string) *PermissionRequestUpdate {
	_u.mutation.SetTableName(v)
	return _u
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableTableName(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetTableName(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *PermissionRequestUpdate) SetActions(v string) *PermissionRequestUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// SetNillableActions sets the "actions" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableActions(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetActions(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *PermissionRequestUpdate) SetReason(v string) *PermissionRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableReason(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PermissionRequestUpdate) SetStatus(v string) *PermissionRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableStatus(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApproverID sets the "approver_id" field.
func (_u *PermissionRequestUpdate) SetApproverID(v int64) *PermissionRequestUpdate {
	_u.mutation.ResetApproverID()
	_u.mutation.SetApproverID(v)
	return _u
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableApproverID(v *int64) *PermissionRequestUpdate {
	if v != nil {
		_u.SetApproverID(*v)
	}
	return _u
}

// AddApproverID adds value to the "approver_id" field.
func (_u *PermissionRequestUpdate) AddApproverID(v int64) *PermissionRequestUpdate {
	_u.mutation.AddApproverID(v)
	return _u
}

// ClearApproverID clears the value of the "approver_id" field.
func (_u *PermissionRequestUpdate) ClearApproverID() *PermissionRequestUpdate {
	_u.mutation.ClearApproverID()
	return _u
}

// SetApproveComment sets the "approve_comment" field.
func (_u *PermissionRequestUpdate) SetApproveComment(v string) *PermissionRequestUpdate {
	_u.mutation.SetApproveComment(v)
	return _u
}

// SetNillableApproveComment sets the "approve_comment" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableApproveComment(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetApproveComment(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *PermissionRequestUpdate) SetApprovedAt(v time.Time) *PermissionRequestUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableApprovedAt(v *time.Time) *PermissionRequestUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *PermissionRequestUpdate) ClearApprovedAt() *PermissionRequestUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PermissionRequestUpdate) SetExpiresAt(v time.Time) *PermissionRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableExpiresAt(v *time.Time) *PermissionRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *PermissionRequestUpdate) SetRevokedAt(v time.Time) *PermissionRequestUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableRevokedAt(v *time.Time) *PermissionRequestUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *PermissionRequestUpdate) ClearRevokedAt() *PermissionRequestUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedBy sets the "revoked_by" field.
func (_u *PermissionRequestUpdate) SetRevokedBy(v int64) *PermissionRequestUpdate {
	_u.mutation.ResetRevokedBy()
	_u.mutation.SetRevokedBy(v)
	return _u
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableRevokedBy(v *int64) *PermissionRequestUpdate {
	if v != nil {
		_u.SetRevokedBy(*v)
	}
	return _u
}

// AddRevokedBy adds value to the "revoked_by" field.
func (_u *PermissionRequestUpdate) AddRevokedBy(v int64) *PermissionRequestUpdate {
	_u.mutation.AddRevokedBy(v)
	return _u
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (_u *PermissionRequestUpdate) ClearRevokedBy() *PermissionRequestUpdate {
	_u.mutation.ClearRevokedBy()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *PermissionRequestUpdate) SetRevokeReason(v string) *PermissionRequestUpdate {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableRevokeReason(v *string) *PermissionRequestUpdate {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PermissionRequestUpdate) SetCreatedAt(v time.Time) *PermissionRequestUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PermissionRequestUpdate) SetNillableCreatedAt(v *time.Time) *PermissionRequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PermissionRequestUpdate) SetUpdatedAt(v time.Time) *PermissionRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PermissionRequestMutation object of the builder.
func (_u *PermissionRequestUpdate) Mutation() *PermissionRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermissionRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermissionRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PermissionRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := permissionrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionRequestUpdate) check() error {
	if v, ok := _u.mutation.Database(); ok {
		if err := permissionrequest.DatabaseValidator(v); err != nil {
			return &ValidationError{Name: "database", err: fmt.Errorf(`ent: validator failed for field "PermissionRequest.database": %w`, err)}
		}
	}
	return nil
}

func (_u *PermissionRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permissionrequest.Table, permissionrequest.Columns, sqlgraph.NewFieldSpec(permissionrequest.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ApplicantID(); ok {
		_spec.SetField(permissionrequest.FieldApplicantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApplicantID(); ok {
		_spec.AddField(permissionrequest.FieldApplicantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DatasourceID(); ok {
		_spec.SetField(permissionrequest.FieldDatasourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDatasourceID(); ok {
		_spec.AddField(permissionrequest.FieldDatasourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Database(); ok {
		_spec.SetField(permissionrequest.FieldDatabase, field.TypeString, value)
	}
	if value, ok := _u.mutation.TableName(); ok {
		_spec.SetField(permissionrequest.FieldTableName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(permissionrequest.FieldActions, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(permissionrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(permissionrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApproverID(); ok {
		_spec.SetField(permissionrequest.FieldApproverID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApproverID(); ok {
		_spec.AddField(permissionrequest.FieldApproverID, field.TypeInt64, value)
	}
	if _u.mutation.ApproverIDCleared() {
		_spec.ClearField(permissionrequest.FieldApproverID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ApproveComment(); ok {
		_spec.SetField(permissionrequest.FieldApproveComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(permissionrequest.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(permissionrequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(permissionrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(permissionrequest.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(permissionrequest.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedBy(); ok {
		_spec.SetField(permissionrequest.FieldRevokedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevokedBy(); ok {
		_spec.AddField(permissionrequest.FieldRevokedBy, field.TypeInt64, value)
	}
	if _u.mutation.RevokedByCleared() {
		_spec.ClearField(permissionrequest.FieldRevokedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(permissionrequest.FieldRevokeReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(permissionrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(permissionrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissionrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermissionRequestUpdateOne is the builder for updating a single PermissionRequest entity.
type PermissionRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermissionRequestMutation
}

// SetApplicantID sets the "applicant_id" field.
func (_u *PermissionRequestUpdateOne) SetApplicantID(v int64) *PermissionRequestUpdateOne {
	_u.mutation.ResetApplicantID()
	_u.mutation.SetApplicantID(v)
	return _u
}

// SetNillableApplicantID sets the "applicant_id" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableApplicantID(v *int64) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetApplicantID(*v)
	}
	return _u
}

// AddApplicantID adds value to the "applicant_id" field.
func (_u *PermissionRequestUpdateOne) AddApplicantID(v int64) *PermissionRequestUpdateOne {
	_u.mutation.AddApplicantID(v)
	return _u
}

// SetDatasourceID sets the "datasource_id" field.
func (_u *PermissionRequestUpdateOne) SetDatasourceID(v int64) *PermissionRequestUpdateOne {
	_u.mutation.ResetDatasourceID()
	_u.mutation.SetDatasourceID(v)
	return _u
}

// SetNillableDatasourceID sets the "datasource_id" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableDatasourceID(v *int64) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetDatasourceID(*v)
	}
	return _u
}

// AddDatasourceID adds value to the "datasource_id" field.
func (_u *PermissionRequestUpdateOne) AddDatasourceID(v int64) *PermissionRequestUpdateOne {
	_u.mutation.AddDatasourceID(v)
	return _u
}

// SetDatabase sets the "database" field.
func (_u *PermissionRequestUpdateOne) SetDatabase(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetDatabase(v)
	return _u
}

// SetNillableDatabase sets the "database" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableDatabase(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetDatabase(*v)
	}
	return _u
}

// SetTableName sets the "table_name" field.
func (_u *PermissionRequestUpdateOne) SetTableName(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetTableName(v)
	return _u
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableTableName(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetTableName(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *PermissionRequestUpdateOne) SetActions(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// SetNillableActions sets the "actions" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableActions(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetActions(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *PermissionRequestUpdateOne) SetReason(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableReason(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PermissionRequestUpdateOne) SetStatus(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableStatus(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApproverID sets the "approver_id" field.
func (_u *PermissionRequestUpdateOne) SetApproverID(v int64) *PermissionRequestUpdateOne {
	_u.mutation.ResetApproverID()
	_u.mutation.SetApproverID(v)
	return _u
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableApproverID(v *int64) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetApproverID(*v)
	}
	return _u
}

// AddApproverID adds value to the "approver_id" field.
func (_u *PermissionRequestUpdateOne) AddApproverID(v int64) *PermissionRequestUpdateOne {
	_u.mutation.AddApproverID(v)
	return _u
}

// ClearApproverID clears the value of the "approver_id" field.
func (_u *PermissionRequestUpdateOne) ClearApproverID() *PermissionRequestUpdateOne {
	_u.mutation.ClearApproverID()
	return _u
}

// SetApproveComment sets the "approve_comment" field.
func (_u *PermissionRequestUpdateOne) SetApproveComment(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetApproveComment(v)
	return _u
}

// SetNillableApproveComment sets the "approve_comment" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableApproveComment(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetApproveComment(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *PermissionRequestUpdateOne) SetApprovedAt(v time.Time) *PermissionRequestUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableApprovedAt(v *time.Time) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *PermissionRequestUpdateOne) ClearApprovedAt() *PermissionRequestUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PermissionRequestUpdateOne) SetExpiresAt(v time.Time) *PermissionRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *PermissionRequestUpdateOne) SetRevokedAt(v time.Time) *PermissionRequestUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableRevokedAt(v *time.Time) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *PermissionRequestUpdateOne) ClearRevokedAt() *PermissionRequestUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedBy sets the "revoked_by" field.
func (_u *PermissionRequestUpdateOne) SetRevokedBy(v int64) *PermissionRequestUpdateOne {
	_u.mutation.ResetRevokedBy()
	_u.mutation.SetRevokedBy(v)
	return _u
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableRevokedBy(v *int64) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetRevokedBy(*v)
	}
	return _u
}

// AddRevokedBy adds value to the "revoked_by" field.
func (_u *PermissionRequestUpdateOne) AddRevokedBy(v int64) *PermissionRequestUpdateOne {
	_u.mutation.AddRevokedBy(v)
	return _u
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (_u *PermissionRequestUpdateOne) ClearRevokedBy() *PermissionRequestUpdateOne {
	_u.mutation.ClearRevokedBy()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *PermissionRequestUpdateOne) SetRevokeReason(v string) *PermissionRequestUpdateOne {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableRevokeReason(v *string) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PermissionRequestUpdateOne) SetCreatedAt(v time.Time) *PermissionRequestUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PermissionRequestUpdateOne) SetNillableCreatedAt(v *time.Time) *PermissionRequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PermissionRequestUpdateOne) SetUpdatedAt(v time.Time) *PermissionRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PermissionRequestMutation object of the builder.
func (_u *PermissionRequestUpdateOne) Mutation() *PermissionRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the PermissionRequestUpdate builder.
func (_u *PermissionRequestUpdateOne) Where(ps ...predicate.PermissionRequest) *PermissionRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermissionRequestUpdateOne) Select(field string, fields ...string) *PermissionRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PermissionRequest entity.
func (_u *PermissionRequestUpdateOne) Save(ctx context.Context) (*PermissionRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionRequestUpdateOne) SaveX(ctx context.Context) *PermissionRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermissionRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PermissionRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := permissionrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Database(); ok {
		if err := permissionrequest.DatabaseValidator(v); err != nil {
			return &ValidationError{Name: "database", err: fmt.Errorf(`ent: validator failed for field "PermissionRequest.database": %w`, err)}
		}
	}
	return nil
}

func (_u *PermissionRequestUpdateOne) sqlSave(ctx context.Context) (_node *PermissionRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permissionrequest.Table, permissionrequest.Columns, sqlgraph.NewFieldSpec(permissionrequest.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PermissionRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permissionrequest.FieldID)
		for _, f := range fields {
			if !permissionrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permissionrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ApplicantID(); ok {
		_spec.SetField(permissionrequest.FieldApplicantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApplicantID(); ok {
		_spec.AddField(permissionrequest.FieldApplicantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DatasourceID(); ok {
		_spec.SetField(permissionrequest.FieldDatasourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDatasourceID(); ok {
		_spec.AddField(permissionrequest.FieldDatasourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Database(); ok {
		_spec.SetField(permissionrequest.FieldDatabase, field.TypeString, value)
	}
	if value, ok := _u.mutation.TableName(); ok {
		_spec.SetField(permissionrequest.FieldTableName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(permissionrequest.FieldActions, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(permissionrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(permissionrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApproverID(); ok {
		_spec.SetField(permissionrequest.FieldApproverID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApproverID(); ok {
		_spec.AddField(permissionrequest.FieldApproverID, field.TypeInt64, value)
	}
	if _u.mutation.ApproverIDCleared() {
		_spec.ClearField(permissionrequest.FieldApproverID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ApproveComment(); ok {
		_spec.SetField(permissionrequest.FieldApproveComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(permissionrequest.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(permissionrequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(permissionrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(permissionrequest.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(permissionrequest.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedBy(); ok {
		_spec.SetField(permissionrequest.FieldRevokedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevokedBy(); ok {
		_spec.AddField(permissionrequest.FieldRevokedBy, field.TypeInt64, value)
	}
	if _u.mutation.RevokedByCleared() {
		_spec.ClearField(permissionrequest.FieldRevokedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(permissionrequest.FieldRevokeReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(permissionrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(permissionrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PermissionRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissionrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
