// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/permissionrequest"
)

// PermissionRequestCreate is the builder for creating a PermissionRequest entity.
type PermissionRequestCreate struct {
	config
	mutation *PermissionRequestMutation
	hooks    []Hook
}

// SetApplicantID sets the "applicant_id" field.
func (_c *PermissionRequestCreate) SetApplicantID(v int64) *PermissionRequestCreate {
	_c.mutation.SetApplicantID(v)
	return _c
}

// SetDatasourceID sets the "datasource_id" field.
func (_c *PermissionRequestCreate) SetDatasourceID(v int64) *PermissionRequestCreate {
	_c.mutation.SetDatasourceID(v)
	return _c
}

// SetDatabase sets the "database" field.
func (_c *PermissionRequestCreate) SetDatabase(v string) *PermissionRequestCreate {
	_c.mutation.SetDatabase(v)
	return _c
}

// SetTableName sets the "table_name" field.
func (_c *PermissionRequestCreate) SetTableName(v string) *PermissionRequestCreate {
	_c.mutation.SetTableName(v)
	return _c
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableTableName(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetTableName(*v)
	}
	return _c
}

// SetActions sets the "actions" field.
func (_c *PermissionRequestCreate) SetActions(v string) *PermissionRequestCreate {
	_c.mutation.SetActions(v)
	return _c
}

// SetNillableActions sets the "actions" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableActions(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetActions(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *PermissionRequestCreate) SetReason(v string) *PermissionRequestCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableReason(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PermissionRequestCreate) SetStatus(v string) *PermissionRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableStatus(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetApproverID sets the "approver_id" field.
func (_c *PermissionRequestCreate) SetApproverID(v int64) *PermissionRequestCreate {
	_c.mutation.SetApproverID(v)
	return _c
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableApproverID(v *int64) *PermissionRequestCreate {
	if v != nil {
		_c.SetApproverID(*v)
	}
	return _c
}

// SetApproveComment sets the "approve_comment" field.
func (_c *PermissionRequestCreate) SetApproveComment(v string) *PermissionRequestCreate {
	_c.mutation.SetApproveComment(v)
	return _c
}

// SetNillableApproveComment sets the "approve_comment" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableApproveComment(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetApproveComment(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *PermissionRequestCreate) SetApprovedAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableApprovedAt(v *time.Time) *PermissionRequestCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PermissionRequestCreate) SetExpiresAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *PermissionRequestCreate) SetRevokedAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableRevokedAt(v *time.Time) *PermissionRequestCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevokedBy sets the "revoked_by" field.
func (_c *PermissionRequestCreate) SetRevokedBy(v int64) *PermissionRequestCreate {
	_c.mutation.SetRevokedBy(v)
	return _c
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableRevokedBy(v *int64) *PermissionRequestCreate {
	if v != nil {
		_c.SetRevokedBy(*v)
	}
	return _c
}

// SetRevokeReason sets the "revoke_reason" field.
func (_c *PermissionRequestCreate) SetRevokeReason(v string) *PermissionRequestCreate {
	_c.mutation.SetRevokeReason(v)
	return _c
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableRevokeReason(v *string) *PermissionRequestCreate {
	if v != nil {
		_c.SetRevokeReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PermissionRequestCreate) SetCreatedAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableCreatedAt(v *time.Time) *PermissionRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PermissionRequestCreate) SetUpdatedAt(v time.Time) *PermissionRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PermissionRequestCreate) SetNillableUpdatedAt(v *time.Time) *PermissionRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PermissionRequestMutation object of the builder.
func (_c *PermissionRequestCreate) Mutation() *PermissionRequestMutation {
	return _c.mutation
}

// Save creates the PermissionRequest in the database.
func (_c *PermissionRequestCreate) Save(ctx context.Context) (*PermissionRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionRequestCreate) SaveX(ctx context.Context) *PermissionRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PermissionRequestCreate) defaults() {
	if _, ok := _c.mutation.TableName(); !ok {
		v := permissionrequest.DefaultTableName
		_c.mutation.SetTableName(v)
	}
	if _, ok := _c.mutation.Actions(); !ok {
		v := permissionrequest.DefaultActions
		_c.mutation.SetActions(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := permissionrequest.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := permissionrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ApproveComment(); !ok {
		v := permissionrequest.DefaultApproveComment
		_c.mutation.SetApproveComment(v)
	}
	if _, ok := _c.mutation.RevokeReason(); !ok {
		v := permissionrequest.DefaultRevokeReason
		_c.mutation.SetRevokeReason(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := permissionrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := permissionrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionRequestCreate) check() error {
	if _, ok := _c.mutation.ApplicantID(); !ok {
		return &ValidationError{Name: "applicant_id", err: errors.New(`ent: missing required field "PermissionRequest.applicant_id"`)}
	}
	if _, ok := _c.mutation.DatasourceID(); !ok {
		return &ValidationError{Name: "datasource_id", err: errors.New(`ent: missing required field "PermissionRequest.datasource_id"`)}
	}
	if _, ok := _c.mutation.Database(); !ok {
		return &ValidationError{Name: "database", err: errors.New(`ent: missing required field "PermissionRequest.database"`)}
	}
	if v, ok := _c.mutation.Database(); ok {
		if err := permissionrequest.DatabaseValidator(v); err != nil {
			return &ValidationError{Name: "database", err: fmt.Errorf(`ent: validator failed for field "PermissionRequest.database": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TableName(); !ok {
		return &ValidationError{Name: "table_name", err: errors.New(`ent: missing required field "PermissionRequest.table_name"`)}
	}
	if _, ok := _c.mutation.Actions(); !ok {
		return &ValidationError{Name: "actions", err: errors.New(`ent: missing required field "PermissionRequest.actions"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "PermissionRequest.reason"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PermissionRequest.status"`)}
	}
	if _, ok := _c.mutation.ApproveComment(); !ok {
		return &ValidationError{Name: "approve_comment", err: errors.New(`ent: missing required field "PermissionRequest.approve_comment"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "PermissionRequest.expires_at"`)}
	}
	if _, ok := _c.mutation.RevokeReason(); !ok {
		return &ValidationError{Name: "revoke_reason", err: errors.New(`ent: missing required field "PermissionRequest.revoke_reason"`)}
	}
	return nil
}

func (_c *PermissionRequestCreate) sqlSave(ctx context.Context) (*PermissionRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionRequestCreate) createSpec() (*PermissionRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissionrequest.Table, sqlgraph.NewFieldSpec(permissionrequest.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ApplicantID(); ok {
		_spec.SetField(permissionrequest.FieldApplicantID, field.TypeInt64, value)
		_node.ApplicantID = value
	}
	if value, ok := _c.mutation.DatasourceID(); ok {
		_spec.SetField(permissionrequest.FieldDatasourceID, field.TypeInt64, value)
		_node.DatasourceID = value
	}
	if value, ok := _c.mutation.Database(); ok {
		_spec.SetField(permissionrequest.FieldDatabase, field.TypeString, value)
		_node.Database = value
	}
	if value, ok := _c.mutation.TableName(); ok {
		_spec.SetField(permissionrequest.FieldTableName, field.TypeString, value)
		_node.TableName = value
	}
	if value, ok := _c.mutation.Actions(); ok {
		_spec.SetField(permissionrequest.FieldActions, field.TypeString, value)
		_node.Actions = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(permissionrequest.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(permissionrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ApproverID(); ok {
		_spec.SetField(permissionrequest.FieldApproverID, field.TypeInt64, value)
		_node.ApproverID = &value
	}
	if value, ok := _c.mutation.ApproveComment(); ok {
		_spec.SetField(permissionrequest.FieldApproveComment, field.TypeString, value)
		_node.ApproveComment = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(permissionrequest.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(permissionrequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(permissionrequest.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevokedBy(); ok {
		_spec.SetField(permissionrequest.FieldRevokedBy, field.TypeInt64, value)
		_node.RevokedBy = &value
	}
	if value, ok := _c.mutation.RevokeReason(); ok {
		_spec.SetField(permissionrequest.FieldRevokeReason, field.TypeString, value)
		_node.RevokeReason = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(permissionrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(permissionrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PermissionRequestCreateBulk is the builder for creating many PermissionRequest entities in bulk.
type PermissionRequestCreateBulk struct {
	config
	err      error
	builders []*PermissionRequestCreate
}

// Save creates the PermissionRequest entities in the database.
func (_c *PermissionRequestCreateBulk) Save(ctx context.Context) ([]*PermissionRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionRequestCreateBulk) SaveX(ctx context.Context) []*PermissionRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
