// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
	"github.com/whg517/sqlflow/internal/db/ent/sensitivetable"
)

// SensitiveTableDelete is the builder for deleting a SensitiveTable entity.
type SensitiveTableDelete struct {
	config
	hooks    []Hook
	mutation *SensitiveTableMutation
}

// Where appends a list predicates to the SensitiveTableDelete builder.
func (_d *SensitiveTableDelete) Where(ps ...predicate.SensitiveTable) *SensitiveTableDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SensitiveTableDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SensitiveTableDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SensitiveTableDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sensitivetable.Table, sqlgraph.NewFieldSpec(sensitivetable.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SensitiveTableDeleteOne is the builder for deleting a single SensitiveTable entity.
type SensitiveTableDeleteOne struct {
	_d *SensitiveTableDelete
}

// Where appends a list predicates to the SensitiveTableDelete builder.
func (_d *SensitiveTableDeleteOne) Where(ps ...predicate.SensitiveTable) *SensitiveTableDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SensitiveTableDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sensitivetable.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SensitiveTableDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
