// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *UserCreate) SetRole(v string) *UserCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *UserCreate) SetNillableRole(v *string) *UserCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetDingtalkUserID sets the "dingtalk_user_id" field.
func (_c *UserCreate) SetDingtalkUserID(v string) *UserCreate {
	_c.mutation.SetDingtalkUserID(v)
	return _c
}

// SetNillableDingtalkUserID sets the "dingtalk_user_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableDingtalkUserID(v *string) *UserCreate {
	if v != nil {
		_c.SetDingtalkUserID(*v)
	}
	return _c
}

// SetDingtalkUnionID sets the "dingtalk_union_id" field.
func (_c *UserCreate) SetDingtalkUnionID(v string) *UserCreate {
	_c.mutation.SetDingtalkUnionID(v)
	return _c
}

// SetNillableDingtalkUnionID sets the "dingtalk_union_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableDingtalkUnionID(v *string) *UserCreate {
	if v != nil {
		_c.SetDingtalkUnionID(*v)
	}
	return _c
}

// SetOidcSubject sets the "oidc_subject" field.
func (_c *UserCreate) SetOidcSubject(v string) *UserCreate {
	_c.mutation.SetOidcSubject(v)
	return _c
}

// SetNillableOidcSubject sets the "oidc_subject" field if the given value is not nil.
func (_c *UserCreate) SetNillableOidcSubject(v *string) *UserCreate {
	if v != nil {
		_c.SetOidcSubject(*v)
	}
	return _c
}

// SetOidcProvider sets the "oidc_provider" field.
func (_c *UserCreate) SetOidcProvider(v string) *UserCreate {
	_c.mutation.SetOidcProvider(v)
	return _c
}

// SetNillableOidcProvider sets the "oidc_provider" field if the given value is not nil.
func (_c *UserCreate) SetNillableOidcProvider(v *string) *UserCreate {
	if v != nil {
		_c.SetOidcProvider(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := user.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.DingtalkUserID(); !ok {
		v := user.DefaultDingtalkUserID
		_c.mutation.SetDingtalkUserID(v)
	}
	if _, ok := _c.mutation.DingtalkUnionID(); !ok {
		v := user.DefaultDingtalkUnionID
		_c.mutation.SetDingtalkUnionID(v)
	}
	if _, ok := _c.mutation.OidcSubject(); !ok {
		v := user.DefaultOidcSubject
		_c.mutation.SetOidcSubject(v)
	}
	if _, ok := _c.mutation.OidcProvider(); !ok {
		v := user.DefaultOidcProvider
		_c.mutation.SetOidcProvider(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "User.role"`)}
	}
	if _, ok := _c.mutation.OidcSubject(); !ok {
		return &ValidationError{Name: "oidc_subject", err: errors.New(`ent: missing required field "User.oidc_subject"`)}
	}
	if _, ok := _c.mutation.OidcProvider(); !ok {
		return &ValidationError{Name: "oidc_provider", err: errors.New(`ent: missing required field "User.oidc_provider"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.DingtalkUserID(); ok {
		_spec.SetField(user.FieldDingtalkUserID, field.TypeString, value)
		_node.DingtalkUserID = value
	}
	if value, ok := _c.mutation.DingtalkUnionID(); ok {
		_spec.SetField(user.FieldDingtalkUnionID, field.TypeString, value)
		_node.DingtalkUnionID = value
	}
	if value, ok := _c.mutation.OidcSubject(); ok {
		_spec.SetField(user.FieldOidcSubject, field.TypeString, value)
		_node.OidcSubject = value
	}
	if value, ok := _c.mutation.OidcProvider(); ok {
		_spec.SetField(user.FieldOidcProvider, field.TypeString, value)
		_node.OidcProvider = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.Create().
//		SetUsername(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreate) OnConflict(opts ...sql.ConflictOption) *UserUpsertOne {
	_c.conflict = opts
	return &UserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreate) OnConflictColumns(columns ...string) *UserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertOne{
		create: _c,
	}
}

type (
	// UserUpsertOne is the builder for "upsert"-ing
	//  one User node.
	UserUpsertOne struct {
		create *UserCreate
	}

	// UserUpsert is the "OnConflict" setter.
	UserUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsername sets the "username" field.
func (u *UserUpsert) SetUsername(v string) *UserUpsert {
	u.Set(user.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsert) UpdateUsername() *UserUpsert {
	u.SetExcluded(user.FieldUsername)
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsert) SetPasswordHash(v string) *UserUpsert {
	u.Set(user.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsert) UpdatePasswordHash() *UserUpsert {
	u.SetExcluded(user.FieldPasswordHash)
	return u
}

// SetRole sets the "role" field.
func (u *UserUpsert) SetRole(v string) *UserUpsert {
	u.Set(user.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *UserUpsert) UpdateRole() *UserUpsert {
	u.SetExcluded(user.FieldRole)
	return u
}

// SetDingtalkUserID sets the "dingtalk_user_id" field.
func (u *UserUpsert) SetDingtalkUserID(v string) *UserUpsert {
	u.Set(user.FieldDingtalkUserID, v)
	return u
}

// UpdateDingtalkUserID sets the "dingtalk_user_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateDingtalkUserID() *UserUpsert {
	u.SetExcluded(user.FieldDingtalkUserID)
	return u
}

// ClearDingtalkUserID clears the value of the "dingtalk_user_id" field.
func (u *UserUpsert) ClearDingtalkUserID() *UserUpsert {
	u.SetNull(user.FieldDingtalkUserID)
	return u
}

// SetDingtalkUnionID sets the "dingtalk_union_id" field.
func (u *UserUpsert) SetDingtalkUnionID(v string) *UserUpsert {
	u.Set(user.FieldDingtalkUnionID, v)
	return u
}

// UpdateDingtalkUnionID sets the "dingtalk_union_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateDingtalkUnionID() *UserUpsert {
	u.SetExcluded(user.FieldDingtalkUnionID)
	return u
}

// ClearDingtalkUnionID clears the value of the "dingtalk_union_id" field.
func (u *UserUpsert) ClearDingtalkUnionID() *UserUpsert {
	u.SetNull(user.FieldDingtalkUnionID)
	return u
}

// SetOidcSubject sets the "oidc_subject" field.
func (u *UserUpsert) SetOidcSubject(v string) *UserUpsert {
	u.Set(user.FieldOidcSubject, v)
	return u
}

// UpdateOidcSubject sets the "oidc_subject" field to the value that was provided on create.
func (u *UserUpsert) UpdateOidcSubject() *UserUpsert {
	u.SetExcluded(user.FieldOidcSubject)
	return u
}

// SetOidcProvider sets the "oidc_provider" field.
func (u *UserUpsert) SetOidcProvider(v string) *UserUpsert {
	u.Set(user.FieldOidcProvider, v)
	return u
}

// UpdateOidcProvider sets the "oidc_provider" field to the value that was provided on create.
func (u *UserUpsert) UpdateOidcProvider() *UserUpsert {
	u.SetExcluded(user.FieldOidcProvider)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UserUpsert) SetCreatedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateCreatedAt() *UserUpsert {
	u.SetExcluded(user.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsert) SetUpdatedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateUpdatedAt() *UserUpsert {
	u.SetExcluded(user.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUpsertOne) UpdateNewValues() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUpsertOne) Ignore() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertOne) DoNothing() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreate.OnConflict
// documentation for more info.
func (u *UserUpsertOne) Update(set func(*UserUpsert)) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *UserUpsertOne) SetUsername(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUsername() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsername()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsertOne) SetPasswordHash(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePasswordHash() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetRole sets the "role" field.
func (u *UserUpsertOne) SetRole(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateRole() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateRole()
	})
}

// SetDingtalkUserID sets the "dingtalk_user_id" field.
func (u *UserUpsertOne) SetDingtalkUserID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetDingtalkUserID(v)
	})
}

// UpdateDingtalkUserID sets the "dingtalk_user_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateDingtalkUserID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDingtalkUserID()
	})
}

// ClearDingtalkUserID clears the value of the "dingtalk_user_id" field.
func (u *UserUpsertOne) ClearDingtalkUserID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearDingtalkUserID()
	})
}

// SetDingtalkUnionID sets the "dingtalk_union_id" field.
func (u *UserUpsertOne) SetDingtalkUnionID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetDingtalkUnionID(v)
	})
}

// UpdateDingtalkUnionID sets the "dingtalk_union_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateDingtalkUnionID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDingtalkUnionID()
	})
}

// ClearDingtalkUnionID clears the value of the "dingtalk_union_id" field.
func (u *UserUpsertOne) ClearDingtalkUnionID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearDingtalkUnionID()
	})
}

// SetOidcSubject sets the "oidc_subject" field.
func (u *UserUpsertOne) SetOidcSubject(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetOidcSubject(v)
	})
}

// UpdateOidcSubject sets the "oidc_subject" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateOidcSubject() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateOidcSubject()
	})
}

// SetOidcProvider sets the "oidc_provider" field.
func (u *UserUpsertOne) SetOidcProvider(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetOidcProvider(v)
	})
}

// UpdateOidcProvider sets the "oidc_provider" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateOidcProvider() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateOidcProvider()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserUpsertOne) SetCreatedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCreatedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsertOne) SetUpdatedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUpdatedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
	conflict []sql.ConflictOption
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUpsertBulk {
	_c.conflict = opts
	return &UserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflictColumns(columns ...string) *UserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertBulk{
		create: _c,
	}
}

// UserUpsertBulk is the builder for "upsert"-ing
// a bulk of User nodes.
type UserUpsertBulk struct {
	create *UserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUpsertBulk) UpdateNewValues() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUpsertBulk) Ignore() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertBulk) DoNothing() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreateBulk.OnConflict
// documentation for more info.
func (u *UserUpsertBulk) Update(set func(*UserUpsert)) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *UserUpsertBulk) SetUsername(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUsername() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsername()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsertBulk) SetPasswordHash(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePasswordHash() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetRole sets the "role" field.
func (u *UserUpsertBulk) SetRole(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateRole() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateRole()
	})
}

// SetDingtalkUserID sets the "dingtalk_user_id" field.
func (u *UserUpsertBulk) SetDingtalkUserID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetDingtalkUserID(v)
	})
}

// UpdateDingtalkUserID sets the "dingtalk_user_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateDingtalkUserID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDingtalkUserID()
	})
}

// ClearDingtalkUserID clears the value of the "dingtalk_user_id" field.
func (u *UserUpsertBulk) ClearDingtalkUserID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearDingtalkUserID()
	})
}

// SetDingtalkUnionID sets the "dingtalk_union_id" field.
func (u *UserUpsertBulk) SetDingtalkUnionID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetDingtalkUnionID(v)
	})
}

// UpdateDingtalkUnionID sets the "dingtalk_union_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateDingtalkUnionID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDingtalkUnionID()
	})
}

// ClearDingtalkUnionID clears the value of the "dingtalk_union_id" field.
func (u *UserUpsertBulk) ClearDingtalkUnionID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearDingtalkUnionID()
	})
}

// SetOidcSubject sets the "oidc_subject" field.
func (u *UserUpsertBulk) SetOidcSubject(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetOidcSubject(v)
	})
}

// UpdateOidcSubject sets the "oidc_subject" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateOidcSubject() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateOidcSubject()
	})
}

// SetOidcProvider sets the "oidc_provider" field.
func (u *UserUpsertBulk) SetOidcProvider(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetOidcProvider(v)
	})
}

// UpdateOidcProvider sets the "oidc_provider" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateOidcProvider() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateOidcProvider()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserUpsertBulk) SetCreatedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCreatedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsertBulk) SetUpdatedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUpdatedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
