// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/whg517/sqlflow/internal/db/ent/webhooksubscription"
)

// WebhookSubscriptionCreate is the builder for creating a WebhookSubscription entity.
type WebhookSubscriptionCreate struct {
	config
	mutation *WebhookSubscriptionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *WebhookSubscriptionCreate) SetName(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *WebhookSubscriptionCreate) SetURL(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetEncryptedSecret sets the "encrypted_secret" field.
func (_c *WebhookSubscriptionCreate) SetEncryptedSecret(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetEncryptedSecret(v)
	return _c
}

// SetEvents sets the "events" field.
func (_c *WebhookSubscriptionCreate) SetEvents(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetEvents(v)
	return _c
}

// SetNillableEvents sets the "events" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableEvents(v *string) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetEvents(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *WebhookSubscriptionCreate) SetEnabled(v bool) *WebhookSubscriptionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableEnabled(v *bool) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *WebhookSubscriptionCreate) SetFailureCount(v int64) *WebhookSubscriptionCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableFailureCount(v *int64) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_c *WebhookSubscriptionCreate) SetLastTriggeredAt(v time.Time) *WebhookSubscriptionCreate {
	_c.mutation.SetLastTriggeredAt(v)
	return _c
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableLastTriggeredAt(v *time.Time) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetLastTriggeredAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *WebhookSubscriptionCreate) SetCreatedBy(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableCreatedBy(v *string) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookSubscriptionCreate) SetCreatedAt(v time.Time) *WebhookSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebhookSubscriptionCreate) SetUpdatedAt(v time.Time) *WebhookSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WebhookSubscriptionMutation object of the builder.
func (_c *WebhookSubscriptionCreate) Mutation() *WebhookSubscriptionMutation {
	return _c.mutation
}

// Save creates the WebhookSubscription in the database.
func (_c *WebhookSubscriptionCreate) Save(ctx context.Context) (*WebhookSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookSubscriptionCreate) SaveX(ctx context.Context) *WebhookSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Events(); !ok {
		v := webhooksubscription.DefaultEvents
		_c.mutation.SetEvents(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := webhooksubscription.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := webhooksubscription.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := webhooksubscription.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webhooksubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webhooksubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookSubscriptionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "WebhookSubscription.name"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "WebhookSubscription.url"`)}
	}
	if _, ok := _c.mutation.EncryptedSecret(); !ok {
		return &ValidationError{Name: "encrypted_secret", err: errors.New(`ent: missing required field "WebhookSubscription.encrypted_secret"`)}
	}
	if _, ok := _c.mutation.Events(); !ok {
		return &ValidationError{Name: "events", err: errors.New(`ent: missing required field "WebhookSubscription.events"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "WebhookSubscription.enabled"`)}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "WebhookSubscription.failure_count"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "WebhookSubscription.created_by"`)}
	}
	return nil
}

func (_c *WebhookSubscriptionCreate) sqlSave(ctx context.Context) (*WebhookSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookSubscriptionCreate) createSpec() (*WebhookSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhooksubscription.Table, sqlgraph.NewFieldSpec(webhooksubscription.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(webhooksubscription.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(webhooksubscription.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.EncryptedSecret(); ok {
		_spec.SetField(webhooksubscription.FieldEncryptedSecret, field.TypeString, value)
		_node.EncryptedSecret = value
	}
	if value, ok := _c.mutation.Events(); ok {
		_spec.SetField(webhooksubscription.FieldEvents, field.TypeString, value)
		_node.Events = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(webhooksubscription.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(webhooksubscription.FieldFailureCount, field.TypeInt64, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.LastTriggeredAt(); ok {
		_spec.SetField(webhooksubscription.FieldLastTriggeredAt, field.TypeTime, value)
		_node.LastTriggeredAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(webhooksubscription.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhooksubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webhooksubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WebhookSubscriptionCreateBulk is the builder for creating many WebhookSubscription entities in bulk.
type WebhookSubscriptionCreateBulk struct {
	config
	err      error
	builders []*WebhookSubscriptionCreate
}

// Save creates the WebhookSubscription entities in the database.
func (_c *WebhookSubscriptionCreateBulk) Save(ctx context.Context) ([]*WebhookSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebhookSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookSubscriptionCreateBulk) SaveX(ctx context.Context) []*WebhookSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
