// Code generated by ent, DO NOT EDIT.

package approvalrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/whg517/sqlflow/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldTicketID, v))
}

// PolicyID applies equality check predicate on the "policy_id" field. It's identical to PolicyIDEQ.
func PolicyID(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldPolicyID, v))
}

// Stage applies equality check predicate on the "stage" field. It's identical to StageEQ.
func Stage(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldStage, v))
}

// TotalStages applies equality check predicate on the "total_stages" field. It's identical to TotalStagesEQ.
func TotalStages(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldTotalStages, v))
}

// ApproverRole applies equality check predicate on the "approver_role" field. It's identical to ApproverRoleEQ.
func ApproverRole(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldApproverRole, v))
}

// ApproverID applies equality check predicate on the "approver_id" field. It's identical to ApproverIDEQ.
func ApproverID(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldApproverID, v))
}

// ApproverName applies equality check predicate on the "approver_name" field. It's identical to ApproverNameEQ.
func ApproverName(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldApproverName, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldAction, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldComment, v))
}

// AutoApproved applies equality check predicate on the "auto_approved" field. It's identical to AutoApprovedEQ.
func AutoApproved(v bool) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldAutoApproved, v))
}

// AutoReason applies equality check predicate on the "auto_reason" field. It's identical to AutoReasonEQ.
func AutoReason(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldAutoReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDGT applies the GT predicate on the "ticket_id" field.
func TicketIDGT(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldTicketID, v))
}

// TicketIDGTE applies the GTE predicate on the "ticket_id" field.
func TicketIDGTE(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldTicketID, v))
}

// TicketIDLT applies the LT predicate on the "ticket_id" field.
func TicketIDLT(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldTicketID, v))
}

// TicketIDLTE applies the LTE predicate on the "ticket_id" field.
func TicketIDLTE(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldTicketID, v))
}

// PolicyIDEQ applies the EQ predicate on the "policy_id" field.
func PolicyIDEQ(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldPolicyID, v))
}

// PolicyIDNEQ applies the NEQ predicate on the "policy_id" field.
func PolicyIDNEQ(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldPolicyID, v))
}

// PolicyIDIn applies the In predicate on the "policy_id" field.
func PolicyIDIn(vs ...int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldPolicyID, vs...))
}

// PolicyIDNotIn applies the NotIn predicate on the "policy_id" field.
func PolicyIDNotIn(vs ...int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldPolicyID, vs...))
}

// PolicyIDGT applies the GT predicate on the "policy_id" field.
func PolicyIDGT(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldPolicyID, v))
}

// PolicyIDGTE applies the GTE predicate on the "policy_id" field.
func PolicyIDGTE(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldPolicyID, v))
}

// PolicyIDLT applies the LT predicate on the "policy_id" field.
func PolicyIDLT(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldPolicyID, v))
}

// PolicyIDLTE applies the LTE predicate on the "policy_id" field.
func PolicyIDLTE(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldPolicyID, v))
}

// PolicyIDIsNil applies the IsNil predicate on the "policy_id" field.
func PolicyIDIsNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIsNull(FieldPolicyID))
}

// PolicyIDNotNil applies the NotNil predicate on the "policy_id" field.
func PolicyIDNotNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotNull(FieldPolicyID))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldStage, vs...))
}

// StageGT applies the GT predicate on the "stage" field.
func StageGT(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldStage, v))
}

// StageGTE applies the GTE predicate on the "stage" field.
func StageGTE(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldStage, v))
}

// StageLT applies the LT predicate on the "stage" field.
func StageLT(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldStage, v))
}

// StageLTE applies the LTE predicate on the "stage" field.
func StageLTE(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldStage, v))
}

// TotalStagesEQ applies the EQ predicate on the "total_stages" field.
func TotalStagesEQ(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldTotalStages, v))
}

// TotalStagesNEQ applies the NEQ predicate on the "total_stages" field.
func TotalStagesNEQ(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldTotalStages, v))
}

// TotalStagesIn applies the In predicate on the "total_stages" field.
func TotalStagesIn(vs ...int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldTotalStages, vs...))
}

// TotalStagesNotIn applies the NotIn predicate on the "total_stages" field.
func TotalStagesNotIn(vs ...int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldTotalStages, vs...))
}

// TotalStagesGT applies the GT predicate on the "total_stages" field.
func TotalStagesGT(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldTotalStages, v))
}

// TotalStagesGTE applies the GTE predicate on the "total_stages" field.
func TotalStagesGTE(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldTotalStages, v))
}

// TotalStagesLT applies the LT predicate on the "total_stages" field.
func TotalStagesLT(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldTotalStages, v))
}

// TotalStagesLTE applies the LTE predicate on the "total_stages" field.
func TotalStagesLTE(v int) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldTotalStages, v))
}

// ApproverRoleEQ applies the EQ predicate on the "approver_role" field.
func ApproverRoleEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldApproverRole, v))
}

// ApproverRoleNEQ applies the NEQ predicate on the "approver_role" field.
func ApproverRoleNEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldApproverRole, v))
}

// ApproverRoleIn applies the In predicate on the "approver_role" field.
func ApproverRoleIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldApproverRole, vs...))
}

// ApproverRoleNotIn applies the NotIn predicate on the "approver_role" field.
func ApproverRoleNotIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldApproverRole, vs...))
}

// ApproverRoleGT applies the GT predicate on the "approver_role" field.
func ApproverRoleGT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldApproverRole, v))
}

// ApproverRoleGTE applies the GTE predicate on the "approver_role" field.
func ApproverRoleGTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldApproverRole, v))
}

// ApproverRoleLT applies the LT predicate on the "approver_role" field.
func ApproverRoleLT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldApproverRole, v))
}

// ApproverRoleLTE applies the LTE predicate on the "approver_role" field.
func ApproverRoleLTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldApproverRole, v))
}

// ApproverRoleContains applies the Contains predicate on the "approver_role" field.
func ApproverRoleContains(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContains(FieldApproverRole, v))
}

// ApproverRoleHasPrefix applies the HasPrefix predicate on the "approver_role" field.
func ApproverRoleHasPrefix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasPrefix(FieldApproverRole, v))
}

// ApproverRoleHasSuffix applies the HasSuffix predicate on the "approver_role" field.
func ApproverRoleHasSuffix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasSuffix(FieldApproverRole, v))
}

// ApproverRoleEqualFold applies the EqualFold predicate on the "approver_role" field.
func ApproverRoleEqualFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEqualFold(FieldApproverRole, v))
}

// ApproverRoleContainsFold applies the ContainsFold predicate on the "approver_role" field.
func ApproverRoleContainsFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContainsFold(FieldApproverRole, v))
}

// ApproverIDEQ applies the EQ predicate on the "approver_id" field.
func ApproverIDEQ(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldApproverID, v))
}

// ApproverIDNEQ applies the NEQ predicate on the "approver_id" field.
func ApproverIDNEQ(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldApproverID, v))
}

// ApproverIDIn applies the In predicate on the "approver_id" field.
func ApproverIDIn(vs ...int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldApproverID, vs...))
}

// ApproverIDNotIn applies the NotIn predicate on the "approver_id" field.
func ApproverIDNotIn(vs ...int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldApproverID, vs...))
}

// ApproverIDGT applies the GT predicate on the "approver_id" field.
func ApproverIDGT(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldApproverID, v))
}

// ApproverIDGTE applies the GTE predicate on the "approver_id" field.
func ApproverIDGTE(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldApproverID, v))
}

// ApproverIDLT applies the LT predicate on the "approver_id" field.
func ApproverIDLT(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldApproverID, v))
}

// ApproverIDLTE applies the LTE predicate on the "approver_id" field.
func ApproverIDLTE(v int64) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldApproverID, v))
}

// ApproverIDIsNil applies the IsNil predicate on the "approver_id" field.
func ApproverIDIsNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIsNull(FieldApproverID))
}

// ApproverIDNotNil applies the NotNil predicate on the "approver_id" field.
func ApproverIDNotNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotNull(FieldApproverID))
}

// ApproverNameEQ applies the EQ predicate on the "approver_name" field.
func ApproverNameEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldApproverName, v))
}

// ApproverNameNEQ applies the NEQ predicate on the "approver_name" field.
func ApproverNameNEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldApproverName, v))
}

// ApproverNameIn applies the In predicate on the "approver_name" field.
func ApproverNameIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldApproverName, vs...))
}

// ApproverNameNotIn applies the NotIn predicate on the "approver_name" field.
func ApproverNameNotIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldApproverName, vs...))
}

// ApproverNameGT applies the GT predicate on the "approver_name" field.
func ApproverNameGT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldApproverName, v))
}

// ApproverNameGTE applies the GTE predicate on the "approver_name" field.
func ApproverNameGTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldApproverName, v))
}

// ApproverNameLT applies the LT predicate on the "approver_name" field.
func ApproverNameLT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldApproverName, v))
}

// ApproverNameLTE applies the LTE predicate on the "approver_name" field.
func ApproverNameLTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldApproverName, v))
}

// ApproverNameContains applies the Contains predicate on the "approver_name" field.
func ApproverNameContains(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContains(FieldApproverName, v))
}

// ApproverNameHasPrefix applies the HasPrefix predicate on the "approver_name" field.
func ApproverNameHasPrefix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasPrefix(FieldApproverName, v))
}

// ApproverNameHasSuffix applies the HasSuffix predicate on the "approver_name" field.
func ApproverNameHasSuffix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasSuffix(FieldApproverName, v))
}

// ApproverNameIsNil applies the IsNil predicate on the "approver_name" field.
func ApproverNameIsNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIsNull(FieldApproverName))
}

// ApproverNameNotNil applies the NotNil predicate on the "approver_name" field.
func ApproverNameNotNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotNull(FieldApproverName))
}

// ApproverNameEqualFold applies the EqualFold predicate on the "approver_name" field.
func ApproverNameEqualFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEqualFold(FieldApproverName, v))
}

// ApproverNameContainsFold applies the ContainsFold predicate on the "approver_name" field.
func ApproverNameContainsFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContainsFold(FieldApproverName, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContainsFold(FieldAction, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContainsFold(FieldComment, v))
}

// AutoApprovedEQ applies the EQ predicate on the "auto_approved" field.
func AutoApprovedEQ(v bool) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldAutoApproved, v))
}

// AutoApprovedNEQ applies the NEQ predicate on the "auto_approved" field.
func AutoApprovedNEQ(v bool) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldAutoApproved, v))
}

// AutoReasonEQ applies the EQ predicate on the "auto_reason" field.
func AutoReasonEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldAutoReason, v))
}

// AutoReasonNEQ applies the NEQ predicate on the "auto_reason" field.
func AutoReasonNEQ(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldAutoReason, v))
}

// AutoReasonIn applies the In predicate on the "auto_reason" field.
func AutoReasonIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldAutoReason, vs...))
}

// AutoReasonNotIn applies the NotIn predicate on the "auto_reason" field.
func AutoReasonNotIn(vs ...string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldAutoReason, vs...))
}

// AutoReasonGT applies the GT predicate on the "auto_reason" field.
func AutoReasonGT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldAutoReason, v))
}

// AutoReasonGTE applies the GTE predicate on the "auto_reason" field.
func AutoReasonGTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldAutoReason, v))
}

// AutoReasonLT applies the LT predicate on the "auto_reason" field.
func AutoReasonLT(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldAutoReason, v))
}

// AutoReasonLTE applies the LTE predicate on the "auto_reason" field.
func AutoReasonLTE(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldAutoReason, v))
}

// AutoReasonContains applies the Contains predicate on the "auto_reason" field.
func AutoReasonContains(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContains(FieldAutoReason, v))
}

// AutoReasonHasPrefix applies the HasPrefix predicate on the "auto_reason" field.
func AutoReasonHasPrefix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasPrefix(FieldAutoReason, v))
}

// AutoReasonHasSuffix applies the HasSuffix predicate on the "auto_reason" field.
func AutoReasonHasSuffix(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldHasSuffix(FieldAutoReason, v))
}

// AutoReasonIsNil applies the IsNil predicate on the "auto_reason" field.
func AutoReasonIsNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIsNull(FieldAutoReason))
}

// AutoReasonNotNil applies the NotNil predicate on the "auto_reason" field.
func AutoReasonNotNil() predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotNull(FieldAutoReason))
}

// AutoReasonEqualFold applies the EqualFold predicate on the "auto_reason" field.
func AutoReasonEqualFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEqualFold(FieldAutoReason, v))
}

// AutoReasonContainsFold applies the ContainsFold predicate on the "auto_reason" field.
func AutoReasonContainsFold(v string) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldContainsFold(FieldAutoReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApprovalRecord) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApprovalRecord) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApprovalRecord) predicate.ApprovalRecord {
	return predicate.ApprovalRecord(sql.NotPredicates(p))
}
